#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, collections

W = []
def block(topic, rows):
    for en, pos, ko, level in rows:
        W.append((en.lower(), pos, ko, level, topic))

# =========================================================
# 기술컴퓨팅  Technology & computing
# =========================================================
block("기술컴퓨팅", [
("algorithm","n","알고리즘","B2"),("database","n","데이터베이스","B2"),
("encryption","n","암호화","C1"),("interface","n","인터페이스","B2"),
("automation","n","자동화","B2"),("prototype","n","시제품, 원형","B2"),
("bandwidth","n","대역폭","C1"),("cache","n","캐시, 임시 저장소","C1"),
("compiler","n","컴파일러","C1"),("firmware","n","펌웨어","C1"),
("latency","n","지연 시간","C1"),("protocol","n","프로토콜, 규약","B2"),
("processor","n","프로세서","B2"),("semiconductor","n","반도체","C1"),
("transistor","n","트랜지스터","C1"),("binary","adj","이진의","B2"),
("cryptography","n","암호학","C2"),("cybersecurity","n","사이버 보안","C1"),
("firewall","n","방화벽","C1"),("malware","n","악성 소프트웨어","C1"),
("authentication","n","인증","C1"),("compression","n","압축","C1"),
("buffer","n","완충 장치, 버퍼","C1"),("recursion","n","재귀","C2"),
("iteration","n","반복","C1"),("runtime","n","실행 시간","C1"),
("debugging","n","디버깅, 오류 수정","C1"),("syntax","n","구문","C1"),
("framework","n","프레임워크, 체계","B2"),("repository","n","저장소","C1"),
("deployment","n","배포","C1"),("virtualization","n","가상화","C2"),
("scalability","n","확장성","C1"),("redundancy","n","중복성, 여분","C1"),
("throughput","n","처리량","C1"),("telemetry","n","원격 측정","C2"),
("interoperability","n","상호 운용성","C2"),("integration","n","통합","B2"),
("configuration","n","구성, 환경 설정","C1"),("optimization","n","최적화","C1"),
("simulation","n","시뮬레이션, 모의실험","B2"),("computation","n","계산","C1"),
("digitization","n","디지털화","C1"),("encode","v","부호화하다","C1"),
("decode","v","해독하다","C1"),("encrypt","v","암호화하다","C1"),
("transmit","v","전송하다","B2"),("transmission","n","전송","B2"),
("wireless","adj","무선의","B2"),("broadband","n","광대역","B2"),
("router","n","라우터","B2"),("gateway","n","관문, 게이트웨이","B2"),
("node","n","노드, 마디","C1"),("cluster","n","무리, 집합","B2"),
("mainframe","n","메인프레임","C1"),("peripheral","n","주변 장치","C1"),
("sensor","n","센서","B2"),("microprocessor","n","마이크로프로세서","C1"),
("nanotechnology","n","나노 기술","C1"),("robotics","n","로봇 공학","C1"),
("neural","adj","신경의","C1"),("heuristic","adj","발견적, 경험적","C2"),
("pixel","n","화소","B2"),("resolution","n","해상도","B2"),
("rendering","n","렌더링, 표현","C1"),("metadata","n","메타데이터","C1"),
("indexing","n","색인화","C1"),("retrieval","n","검색, 회수","C1"),
("storage","n","저장","B2"),("backup","n","백업","B2"),
("synchronization","n","동기화","C1"),("cipher","n","암호","C2"),
("hash","n","해시","C2"),("quantum","adj","양자의","C1"),
("telecommunication","n","원격 통신","C1"),("satellite","n","위성","B2"),
("surveillance","n","감시","C1"),("biometric","adj","생체 인식의","C1"),
("usability","n","사용성","C1"),("emulate","v","모방하다","C2"),
("emulator","n","에뮬레이터","C2"),("streaming","n","스트리밍","B2"),
("cloud","n","클라우드","B2"),("augmented","adj","증강된","C1"),
("immersive","adj","몰입형의","C1"),("aggregate","v","집계하다","C1"),
("dataset","n","데이터 집합","B2"),("digital","adj","디지털의","B2"),
("analog","adj","아날로그의","B2"),("connectivity","n","연결성","C1"),
("checksum","n","체크섬, 검사합","C2"),("decrypt","v","복호화하다","C1"),
("decompression","n","압축 해제","C2"),("compile","v","컴파일하다","C1"),
("execute","v","실행하다","B2"),("execution","n","실행","B2"),
("modular","adj","모듈식의","C1"),("scalable","adj","확장 가능한","C1"),
("robust","adj","견고한","C1"),("legacy","adj","기존의, 유산의","C1"),
("obsolete","adj","구식의, 쓸모없는","C1"),("proprietary","adj","독점의, 사유의","C2"),
("hypertext","n","하이퍼텍스트","C1"),("algorithmic","adj","알고리즘적인","C1"),
("computational","adj","계산의","C1"),("digitize","v","디지털화하다","C1"),
("automate","v","자동화하다","B2"),("server","n","서버","B2"),
("terminal","n","단말기","B2"),("bug","n","오류, 버그","B2"),
("patch","n","패치, 수정","B2"),("queue","n","대기열","B2"),
("virtual","adj","가상의","B2"),("simulate","v","모의실험하다","B2"),
("innovation","n","혁신","B2"),("innovative","adj","혁신적인","B2"),
("obsolescence","n","노후화, 진부화","C2"),("functionality","n","기능성","C1"),
("specification","n","사양, 명세","C1"),("compatibility","n","호환성","C1"),
("compatible","adj","호환되는","B2"),("upgrade","n","개선, 업그레이드","B2"),
("capacity","n","용량","B2"),("cryptographic","adj","암호의","C2"),
("anonymize","v","익명화하다","C2"),("anonymity","n","익명성","C1"),
("autonomy","n","자율성","C1"),("autonomous","adj","자율적인","C1"),
("artificial","adj","인공의","B2"),("cognition","n","인지","C1"),
("cognitive","adj","인지의","C1"),("archive","n","기록 보관소","B2"),
("archival","adj","기록 보관의","C2"),("digitalization","n","디지털 전환","C2"),
("cybernetic","adj","인공두뇌학의","C2"),("bit","n","비트","B2"),
("byte","n","바이트","B2"),("modem","n","모뎀","B2"),
("cursor","n","커서","B2"),("hyperlink","n","하이퍼링크","B2"),
("template","n","견본, 템플릿","B2"),("plugin","n","플러그인, 확장 기능","B2"),
])

# =========================================================
# 공학  Engineering & materials
# =========================================================
block("공학", [
("mechanism","n","기계 장치, 메커니즘","B2"),("apparatus","n","기구, 장치","C1"),
("alloy","n","합금","C1"),("tensile","adj","인장의","C2"),
("calibrate","v","보정하다","C1"),("infrastructure","n","기반 시설","B2"),
("machinery","n","기계류","B2"),("turbine","n","터빈","C1"),
("combustion","n","연소","C1"),("hydraulic","adj","수압의, 유압의","C1"),
("pneumatic","adj","공기압의","C2"),("thermal","adj","열의","B2"),
("aerodynamic","adj","공기역학의","C1"),("structural","adj","구조의","B2"),
("torque","n","회전력, 토크","C2"),("friction","n","마찰","B2"),
("lubrication","n","윤활","C2"),("bearing","n","베어링, 축받이","C1"),
("piston","n","피스톤","C1"),("valve","n","밸브","B2"),
("cylinder","n","실린더, 원통","B2"),("shaft","n","축, 굴대","C1"),
("chassis","n","차대, 섀시","C2"),("girder","n","대들보","C2"),
("beam","n","들보, 빔","B2"),("truss","n","트러스, 골조","C2"),
("cantilever","n","외팔보, 캔틸레버","C2"),("foundation","n","토대, 기초","B2"),
("reinforcement","n","보강, 강화","C1"),("reinforced","adj","강화된","B2"),
("welding","n","용접","C1"),("forging","n","단조, 벼림","C2"),
("casting","n","주조","C1"),("fabrication","n","제작, 조립","C1"),
("assembly","n","조립","B2"),("component","n","구성 요소, 부품","B2"),
("durability","n","내구성","C1"),("elasticity","n","탄성","C1"),
("plasticity","n","가소성","C2"),("ductility","n","연성","C2"),
("malleable","adj","유연한, 잘 펴지는","C2"),("brittle","adj","부서지기 쉬운","C1"),
("corrosion","n","부식","C1"),("insulation","n","절연, 단열","C1"),
("conductivity","n","전도성","C1"),("resistance","n","저항","B2"),
("voltage","n","전압","B2"),("capacitor","n","축전기","C2"),
("resistor","n","저항기","C1"),("transformer","n","변압기","C1"),
("generator","n","발전기","B2"),("propulsion","n","추진","C2"),
("thrust","n","추진력","C1"),("viscosity","n","점성","C2"),
("density","n","밀도","B2"),("buoyancy","n","부력","C2"),
("vacuum","n","진공","B2"),("tension","n","장력, 긴장","B2"),
("deformation","n","변형","C2"),("fatigue","n","피로, 피로도","C1"),
("fracture","n","골절, 균열","C1"),("resilience","n","회복력, 탄성","C1"),
("rigidity","n","강성, 경직성","C2"),("stiffness","n","뻣뻣함, 강도","C1"),
("aperture","n","조리개, 구멍","C2"),("refraction","n","굴절","C1"),
("wavelength","n","파장","C1"),("amplitude","n","진폭","C1"),
("oscillation","n","진동, 요동","C2"),("vibration","n","진동","B2"),
("resonance","n","공명, 울림","C2"),("acoustics","n","음향학","C2"),
("thermodynamics","n","열역학","C2"),("entropy","n","엔트로피","C2"),
("calibration","n","보정, 눈금 조정","C1"),("precision","n","정밀","B2"),
("tolerance","n","공차, 허용 오차","C1"),("alignment","n","정렬","C1"),
("schematic","n","도해, 회로도","C2"),("blueprint","n","청사진, 설계도","C1"),
("mechanical","adj","기계의","B2"),("kinetic","adj","운동의","C1"),
("momentum","n","운동량, 탄력","C1"),("inertia","n","관성","C2"),
("gravitational","adj","중력의","C1"),("electromagnetic","adj","전자기의","C1"),
("conduit","n","도관, 관로","C2"),("insulator","n","절연체","C1"),
("ceramic","n","도자기, 세라믹","B2"),("polymer","n","중합체, 폴리머","C1"),
("composite","n","합성물, 복합재","C1"),("synthetic","adj","합성의","B2"),
("adhesive","n","접착제","C1"),("coating","n","코팅, 도료","B2"),
("instrumentation","n","계측, 계기류","C2"),("gauge","n","계기, 측정기","C1"),
("throttle","n","조절판, 스로틀","C2"),("actuator","n","작동기","C2"),
("servo","n","서보 기구","C2"),("circuitry","n","회로망","C2"),
("circuit","n","회로","B2"),("dynamo","n","발전기","C2"),
("flywheel","n","플라이휠, 관성 바퀴","C2"),("gear","n","톱니바퀴, 기어","B2"),
("lever","n","지렛대","B2"),("pulley","n","도르래","B2"),
("hinge","n","경첩","B2"),("bracket","n","받침대, 브래킷","B2"),
("flange","n","플랜지, 테두리","C2"),("bolt","n","볼트","B2"),
("rivet","n","리벳, 대갈못","C2"),("weld","v","용접하다","C1"),
("reinforce","v","보강하다","B2"),("corrode","v","부식하다","C1"),
("dilate","v","팽창하다","C2"),("contraction","n","수축","C1"),
("expansion","n","팽창","B2"),("conductance","n","전도율","C2"),
("impedance","n","임피던스, 저항","C2"),("filament","n","필라멘트, 가는 선","C2"),
("electrode","n","전극","C1"),("optics","n","광학","C1"),
("lens","n","렌즈","B2"),("reflection","n","반사","B2"),
("frequency","n","진동수, 주파수","B2"),("modulation","n","변조","C2"),
("transducer","n","변환기","C2"),("hydraulics","n","수력학","C2"),
("aerodynamics","n","공기역학","C1"),("propel","v","추진하다","C1"),
("suspension","n","현가장치, 매달기","C1"),("lattice","n","격자","C2"),
("substrate","n","기질, 기판","C2"),("corrosive","adj","부식성의","C1"),
("combust","v","연소하다","C2"),("ignite","v","점화하다","C1"),
("ignition","n","점화","C1"),("thermoplastic","n","열가소성 물질","C2"),
("galvanize","v","도금하다, 자극하다","C2"),("deflection","n","편향, 처짐","C2"),
("stress","n","응력","B2"),("strain","n","변형력, 부담","B2"),
("deflect","v","방향을 바꾸다","C1"),("flexural","adj","굽힘의","C2"),
])

# =========================================================
# 수학통계  Mathematics & statistics
# =========================================================
block("수학통계", [
("variable","n","변수","B2"),("coefficient","n","계수","C1"),
("probability","n","확률","B2"),("correlation","n","상관관계","C1"),
("exponential","adj","지수의","C1"),("deviation","n","편차","C1"),
("equation","n","방정식","B2"),("function","n","함수","B2"),
("derivative","n","도함수, 미분","C2"),("integral","n","적분","C2"),
("calculus","n","미적분학","C1"),("algebra","n","대수학","B2"),
("geometry","n","기하학","B2"),("theorem","n","정리","C1"),
("axiom","n","공리","C2"),("matrix","n","행렬","C1"),
("vector","n","벡터","C1"),("scalar","n","스칼라","C2"),
("logarithm","n","로그","C2"),("polynomial","n","다항식","C2"),
("quadratic","adj","이차의","C1"),("linear","adj","선형의","C1"),
("nonlinear","adj","비선형의","C1"),("asymptote","n","점근선","C2"),
("tangent","n","접선","C1"),("slope","n","기울기","B2"),
("intercept","n","절편","C1"),("parabola","n","포물선","C1"),
("hyperbola","n","쌍곡선","C2"),("ellipse","n","타원","C1"),
("radius","n","반지름","B2"),("diameter","n","지름","B2"),
("circumference","n","둘레, 원주","B2"),("perimeter","n","둘레","B2"),
("hypotenuse","n","빗변","C2"),("congruent","adj","합동의","C2"),
("symmetry","n","대칭","B2"),("asymmetry","n","비대칭","C1"),
("permutation","n","순열","C2"),("combination","n","조합","B2"),
("factorial","n","계승, 팩토리얼","C2"),("summation","n","합산","C2"),
("product","n","곱","B2"),("quotient","n","몫","C1"),
("remainder","n","나머지","B2"),("numerator","n","분자","C1"),
("denominator","n","분모","C1"),("fraction","n","분수","B2"),
("decimal","n","소수","B2"),("exponent","n","지수","C1"),
("magnitude","n","크기, 규모","C1"),("infinity","n","무한","B2"),
("finite","adj","유한한","C1"),("infinite","adj","무한한","B2"),
("convergence","n","수렴","C2"),("divergence","n","발산","C2"),
("limit","n","극한","B2"),("continuity","n","연속성","C1"),
("discrete","adj","이산의, 별개의","C1"),("distribution","n","분포","C1"),
("histogram","n","히스토그램, 도수분포도","C1"),("median","n","중앙값","B2"),
("mode","n","최빈값","B2"),("mean","n","평균","B2"),
("variance","n","분산","C1"),("quartile","n","사분위수","C2"),
("percentile","n","백분위수","C1"),("skewness","n","왜도","C2"),
("regression","n","회귀","C1"),("covariance","n","공분산","C2"),
("sampling","n","표본 추출","C1"),("estimator","n","추정량","C2"),
("estimate","n","추정치","B2"),("inference","n","추론","C1"),
("hypothesis","n","가설","B2"),("significance","n","유의성, 중요성","B2"),
("confidence","n","신뢰","B2"),("interval","n","구간, 간격","B2"),
("threshold","n","임계값, 문턱","C1"),("margin","n","여백, 오차 범위","B2"),
("outlier","n","이상치","C1"),("bias","n","편향","C1"),
("random","adj","무작위의","B2"),("randomization","n","무작위화","C1"),
("stochastic","adj","확률적인","C2"),("deterministic","adj","결정론적인","C2"),
("probabilistic","adj","확률론적인","C2"),("exponentially","adv","기하급수적으로","C1"),
("logarithmic","adj","로그의","C2"),("proportional","adj","비례하는","B2"),
("proportion","n","비율","B2"),("ratio","n","비, 비율","B2"),
("percentage","n","백분율","B2"),("cumulative","adj","누적의","C1"),
("quantify","v","수량화하다","C1"),("quantifiable","adj","수량화할 수 있는","C2"),
("numerical","adj","수치의","B2"),("approximation","n","근사값","C1"),
("approximate","v","근사하다","B2"),("rounding","n","반올림","B2"),
("interpolation","n","보간","C2"),("extrapolation","n","외삽, 추정","C2"),
("recurrence","n","재발, 점화식","C2"),("sequence","n","수열, 순서","B2"),
("series","n","급수, 연속","B2"),("progression","n","수열, 진행","C1"),
("arithmetic","n","산수, 산술","B2"),("modulus","n","절댓값, 법","C2"),
("absolute","adj","절대의","B2"),("reciprocal","n","역수","C2"),
("inverse","adj","역의","C1"),("differential","adj","미분의","C2"),
("gradient","n","기울기, 경사","C1"),("vertex","n","꼭짓점","C1"),
("coordinate","n","좌표","B2"),("axis","n","축","B2"),
("quadrant","n","사분면","C1"),("dimension","n","차원","B2"),
("dimensional","adj","차원의","C1"),("spatial","adj","공간의","C1"),
("topology","n","위상수학","C2"),("binomial","adj","이항의","C2"),
("normal","adj","정규의","B2"),("parametric","adj","모수의","C2"),
("nonparametric","adj","비모수의","C2"),("statistic","n","통계량","B2"),
("statistical","adj","통계의","B2"),("tabulate","v","표로 만들다","C1"),
("compute","v","계산하다","B2"),("enumerate","v","열거하다","C1"),
("denote","v","나타내다","C1"),("differentiate","v","미분하다, 구별하다","C1"),
("integrate","v","적분하다, 통합하다","C1"),("factor","n","인수, 요인","B2"),
("factorize","v","인수분해하다","C2"),("algebraic","adj","대수의","C1"),
("geometric","adj","기하학의","C1"),("cardinality","n","기수, 농도","C2"),
("subset","n","부분집합","C1"),("superset","n","상위집합","C2"),
("intersection","n","교집합","B2"),("union","n","합집합","B2"),
("complement","n","여집합, 보완","C1"),("null","adj","영의, 공의","C1"),
("eigenvalue","n","고윳값","C2"),
])

# =========================================================
# 연구방법  Research methodology & academic argument
# =========================================================
block("연구방법", [
("methodology","n","방법론","B2"),("replicate","v","복제하다, 재현하다","C1"),
("quantitative","adj","정량적인","C1"),("qualitative","adj","정성적인","C1"),
("validity","n","타당성","C1"),("reliability","n","신뢰도","C1"),
("hypothesize","v","가설을 세우다","C1"),("empirical","adj","경험적인, 실증적인","C1"),
("theoretical","adj","이론적인","B2"),("paradigm","n","패러다임","C2"),
("construct","n","구성 개념","C2"),("confound","v","혼동시키다, 교란하다","C2"),
("confounding","adj","교란하는","C2"),("objectivity","n","객관성","C1"),
("subjectivity","n","주관성","C1"),("generalization","n","일반화","C1"),
("generalize","v","일반화하다","B2"),("infer","v","추론하다","B2"),
("deduce","v","연역하다, 추론하다","C1"),("deduction","n","연역","C1"),
("induction","n","귀납","C1"),("induce","v","유도하다","C1"),
("correlate","v","상관관계가 있다","C1"),("causation","n","인과관계","C1"),
("causal","adj","인과의","C1"),("determinant","n","결정 요인","C1"),
("criterion","n","기준","C1"),("criteria","n","기준들","B2"),
("benchmark","n","기준점","C1"),("procedure","n","절차","B2"),
("systematic","adj","체계적인","B2"),("rigorous","adj","엄격한, 철저한","C1"),
("rigor","n","엄밀함","C2"),("peer","n","동료, 동등한 사람","B2"),
("scrutiny","n","정밀 조사","C1"),("scrutinize","v","면밀히 조사하다","C1"),
("analysis","n","분석","B2"),("analytical","adj","분석적인","B2"),
("synthesis","n","종합, 합성","C1"),("synthesize","v","종합하다","C1"),
("abstract","n","초록, 요약","B2"),("citation","n","인용","C1"),
("cite","v","인용하다","B2"),("reference","n","참고 문헌","B2"),
("bibliography","n","참고 문헌 목록","C1"),("corroborate","v","확증하다","C2"),
("substantiate","v","입증하다","C2"),("refute","v","반박하다","C1"),
("rebut","v","반박하다","C2"),("contradict","v","모순되다","B2"),
("contradiction","n","모순","B2"),("plausible","adj","그럴듯한","C1"),
("plausibility","n","개연성","C2"),("coherent","adj","일관된","C1"),
("coherence","n","일관성","C1"),("consistency","n","일관성","B2"),
("discrepancy","n","불일치, 차이","C1"),("anomaly","n","변칙, 이례","C1"),
("paradox","n","역설","C1"),("premise","n","전제","C1"),
("proposition","n","명제, 제안","C1"),("assertion","n","주장","C1"),
("assert","v","주장하다","B2"),("postulate","v","가정하다","C2"),
("presuppose","v","전제로 하다","C2"),("presumption","n","추정, 가정","C1"),
("assumption","n","가정","B2"),("assume","v","가정하다","B2"),
("conjecture","n","추측","C2"),("speculate","v","추측하다","C1"),
("speculation","n","추측","C1"),("extrapolate","v","추정하다","C2"),
("ascertain","v","확인하다, 규명하다","C2"),("elucidate","v","명료하게 설명하다","C2"),
("delineate","v","상세히 기술하다","C2"),("articulate","v","명확히 표현하다","C1"),
("formulate","v","공식화하다","C1"),("conceptualize","v","개념화하다","C2"),
("operationalize","v","조작적으로 정의하다","C2"),("characterize","v","특징짓다","B2"),
("categorize","v","분류하다","B2"),("classify","v","분류하다","B2"),
("classification","n","분류","B2"),("taxonomy","n","분류 체계","C2"),
("typology","n","유형론","C2"),("dichotomy","n","이분법","C2"),
("spectrum","n","범위, 스펙트럼","C1"),("continuum","n","연속체","C2"),
("facet","n","측면, 양상","C1"),("attribute","n","속성","C1"),
("parameter","n","매개변수","C1"),("metric","n","지표, 측정 기준","C1"),
("indicator","n","지표","B2"),("index","n","지수, 색인","B2"),
("proxy","n","대리 지표","C2"),("sample","n","표본","B2"),
("population","n","모집단","B2"),("cohort","n","집단, 코호트","C2"),
("longitudinal","adj","종단적인","C2"),("retrospective","adj","회고적인","C2"),
("prospective","adj","장래의, 예상되는","C1"),("baseline","n","기준선","C1"),
("standardize","v","표준화하다","C1"),("normalize","v","정규화하다","C1"),
("consolidate","v","통합하다, 강화하다","C1"),("corroboration","n","확증","C2"),
("validation","n","검증","C1"),("verification","n","확인, 검증","C1"),
("verify","v","검증하다","B2"),("falsify","v","반증하다, 위조하다","C2"),
("falsifiable","adj","반증 가능한","C2"),("reproducibility","n","재현성","C2"),
("replicability","n","반복 가능성","C2"),("robustness","n","견고성","C2"),
("sensitivity","n","민감도","C1"),("specificity","n","특이성","C2"),
("accuracy","n","정확성","B2"),("error","n","오차, 오류","B2"),
("artifact","n","인위적 산물","C2"),("skew","v","왜곡하다","C1"),
("distort","v","왜곡하다","B2"),("distortion","n","왜곡","C1"),
("underlying","adj","근본적인","C1"),("fundamental","adj","근본적인","B2"),
("intrinsic","adj","본질적인","C1"),("extrinsic","adj","외적인","C2"),
("inherent","adj","내재된","C1"),("implicit","adj","암시적인","C1"),
("explicit","adj","명시적인","B2"),("ambiguity","n","모호함","C1"),
("ambiguous","adj","모호한","B2"),("nuance","n","미묘한 차이","C1"),
("arbitrary","adj","임의의, 자의적인","C1"),("arbitrarily","adv","임의로","C2"),
("subjective","adj","주관적인","B2"),("objective","adj","객관적인","B2"),
("comprehensive","adj","포괄적인","B2"),("exhaustive","adj","철저한, 총망라한","C1"),
("cursory","adj","대충의, 피상적인","C2"),("tentative","adj","잠정적인","C1"),
("definitive","adj","결정적인, 확정적인","C1"),("conclusive","adj","결정적인","C1"),
("inconclusive","adj","결론이 나지 않은","C1"),("warrant","v","정당화하다","C1"),
("corollary","n","필연적 결과, 따름정리","C2"),
])

# =========================================================
# 농업산업  Agriculture, food & industry
# =========================================================
block("농업산업", [
("irrigation","n","관개","B2"),("cultivation","n","경작, 재배","C1"),
("fertilizer","n","비료","B2"),("yield","n","산출량, 수확량","B2"),
("livestock","n","가축","B2"),("surplus","n","잉여, 과잉","C1"),
("harvest","n","수확","B2"),("crop","n","작물","B2"),
("arable","adj","경작에 적합한","C2"),("fertile","adj","비옥한","B2"),
("fertility","n","비옥함, 생식력","C1"),("barren","adj","척박한, 불모의","C1"),
("soil","n","토양","B2"),("topsoil","n","표토","C2"),
("erosion","n","침식","C1"),("sediment","n","퇴적물, 침전물","C1"),
("nutrient","n","영양분","B2"),("compost","n","퇴비","C1"),
("manure","n","거름, 분뇨","C1"),("pesticide","n","살충제","B2"),
("herbicide","n","제초제","C1"),("insecticide","n","살충제","C1"),
("fungicide","n","살균제","C2"),("pollination","n","수분, 꽃가루받이","C1"),
("germination","n","발아","C2"),("photosynthesis","n","광합성","B2"),
("horticulture","n","원예","C2"),("agronomy","n","농학","C2"),
("aquaculture","n","양식업","C2"),("husbandry","n","사육, 농업 경영","C2"),
("grazing","n","방목","C1"),("pasture","n","목초지","B2"),
("fodder","n","사료, 여물","C2"),("silage","n","저장 사료, 사일리지","C2"),
("tillage","n","경운, 밭갈이","C2"),("plow","v","쟁기질하다","B2"),
("sow","v","씨를 뿌리다","B2"),("reap","v","수확하다","C1"),
("cultivate","v","경작하다, 재배하다","B2"),("irrigate","v","관개하다","C1"),
("fertilize","v","비옥하게 하다","C1"),("propagate","v","번식시키다, 전파하다","C2"),
("propagation","n","번식, 전파","C2"),("hybrid","n","잡종, 혼성물","C1"),
("hybridization","n","잡종화, 교배","C2"),("genetically","adv","유전적으로","C1"),
("transgenic","adj","형질 전환의","C2"),("monoculture","n","단일 경작","C2"),
("rotation","n","윤작, 순환","B2"),("produce","n","농산물","B2"),
("perishable","adj","부패하기 쉬운","C1"),("preservation","n","보존","B2"),
("preserve","v","보존하다","B2"),("refrigeration","n","냉장","C1"),
("pasteurization","n","저온 살균","C2"),("fermentation","n","발효","C1"),
("ferment","v","발효시키다","C1"),("distillation","n","증류","C2"),
("brewing","n","양조","C1"),("processing","n","가공","B2"),
("refinement","n","정제, 세련","C1"),("refine","v","정제하다","B2"),
("extraction","n","추출","C1"),("extract","v","추출하다","B2"),
("byproduct","n","부산물","C1"),("residue","n","잔여물, 찌꺼기","C1"),
("contamination","n","오염","C1"),("contaminate","v","오염시키다","B2"),
("adulteration","n","불순물 섞기","C2"),("spoilage","n","부패, 손상","C2"),
("staple","n","주식, 주요 산물","C1"),("commodity","n","상품, 원자재","C1"),
("cultivar","n","재배 품종","C2"),("breed","v","사육하다, 번식시키다","B2"),
("breeding","n","사육, 번식","B2"),("domestication","n","가축화, 순화","C2"),
("domesticate","v","길들이다","C1"),("poultry","n","가금류","B2"),
("dairy","n","낙농, 유제품","B2"),("cattle","n","소","B2"),
("herd","n","무리, 떼","B2"),("flock","n","떼, 무리","B2"),
("slaughter","n","도살","C1"),("veterinary","adj","수의학의","C1"),
("forage","v","먹이를 찾다","C2"),("drought","n","가뭄","B2"),
("famine","n","기근","C1"),("subsistence","n","최저 생활, 자급","C2"),
("sufficiency","n","충분함, 자급","C2"),("abundance","n","풍부함","C1"),
("scarcity","n","부족, 희소성","C1"),("depletion","n","고갈","C1"),
("deplete","v","고갈시키다","C1"),("sustainable","adj","지속 가능한","B2"),
("sustainability","n","지속 가능성","B2"),("renewable","adj","재생 가능한","B2"),
("reforestation","n","재조림","C2"),("deforestation","n","삼림 벌채","C1"),
("desertification","n","사막화","C2"),("reclamation","n","개간, 매립","C2"),
("terrace","n","계단식 밭","B2"),("greenhouse","n","온실","B2"),
("hydroponics","n","수경 재배","C2"),("mechanization","n","기계화","C2"),
("industrialization","n","산업화","C1"),("manufacturing","n","제조","B2"),
("manufacture","v","제조하다","B2"),("output","n","산출, 생산량","B2"),
("productivity","n","생산성","B2"),("efficiency","n","효율성","B2"),
("warehouse","n","창고","B2"),("inventory","n","재고","C1"),
("logistics","n","물류","C1"),("supply","n","공급","B2"),
("demand","n","수요","B2"),("procurement","n","조달","C2"),
("wholesale","n","도매","C1"),("export","n","수출","B2"),
("import","n","수입","B2"),("tariff","n","관세","C1"),
("quota","n","할당량","C1"),("subsidy","n","보조금","C1"),
("subsidize","v","보조금을 주다","C1"),("exploitation","n","착취, 개발","C1"),
("mining","n","채굴","B2"),("ore","n","광석","C1"),
("smelting","n","제련","C2"),("quarry","n","채석장","C1"),
("timber","n","목재","B2"),("lumber","n","목재","B2"),
("textile","n","직물","C1"),("mill","n","제분소, 공장","B2"),
("refinery","n","정제소, 정유소","C1"),("foundry","n","주조 공장","C2"),
("mechanize","v","기계화하다","C2"),("streamline","v","간소화하다, 능률화하다","C1"),
("overhead","n","간접비","C1"),("cultivable","adj","경작 가능한","C2"),
("agrarian","adj","농업의","C2"),("pastoral","adj","목가적인, 목축의","C1"),
("seasonal","adj","계절의","B2"),("perennial","adj","다년생의","C1"),
("annual","adj","한해살이의, 연례의","B2"),("organic","adj","유기농의","B2"),
("biomass","n","생물량, 바이오매스","C1"),
])

# ---------------- process: dedup, cap per topic, exactly 700 ----------------
TARGET = 700
CAP = 140  # 5 topics x 140 = 700

# nudge distribution toward 35/40/25 by downgrading common words C1->B2
DOWNGRADE = {
 "surveillance","connectivity","fatigue","alignment","momentum","threshold",
 "gradient","progression","benchmark","citation","spectrum","erosion",
 "cultivation","fertility","refrigeration","commodity","scarcity","inventory",
 "tariff","famine","contamination",
}

seen = set()
by_topic = collections.OrderedDict()
dups = []
for en, pos, ko, level, topic in W:
    if en in DOWNGRADE and level == "C1":
        level = "B2"
    if en in seen:
        dups.append(en)
        continue
    seen.add(en)
    by_topic.setdefault(topic, []).append({"en": en, "pos": pos, "ko": ko, "level": level, "topic": topic})

print("duplicates skipped:", dups)
for t, items in by_topic.items():
    print(f"  {t}: {len(items)} unique")

out = []
for t, items in by_topic.items():
    out.extend(items[:CAP])

# safety: if any topic short, we still may be under 700 -> pad from leftovers
if len(out) < TARGET:
    used = {d["en"] for d in out}
    for t, items in by_topic.items():
        for it in items[CAP:]:
            if len(out) >= TARGET:
                break
            if it["en"] not in used:
                out.append(it); used.add(it["en"])
out = out[:TARGET]

with open("/home/user/voca/wordbooks/toefl-build/poolF.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=0)

lv = collections.Counter(d["level"] for d in out)
tp = collections.Counter(d["topic"] for d in out)
n = len(out)
print("\nFINAL COUNT:", n)
print("levels:", dict(lv), {k: f"{v/n*100:.0f}%" for k, v in lv.items()})
print("topics:", dict(tp))
