import json, sys

# (en, pos, ko, level) — academic general / cross-disciplinary vocabulary
data = [
# ---- Academic verbs ----
("analyze","v","분석하다","B2"),
("assess","v","평가하다","B2"),
("evaluate","v","평가하다, 가늠하다","B2"),
("interpret","v","해석하다","B2"),
("identify","v","식별하다, 확인하다","B2"),
("indicate","v","나타내다, 시사하다","B2"),
("illustrate","v","예시하다, 설명하다","B2"),
("demonstrate","v","입증하다, 보여주다","B2"),
("determine","v","규명하다, 결정하다","B2"),
("estimate","v","추정하다","B2"),
("examine","v","조사하다, 검토하다","B2"),
("investigate","v","조사하다, 연구하다","B2"),
("observe","v","관찰하다, 논평하다","B2"),
("define","v","정의하다","B2"),
("describe","v","서술하다, 기술하다","B2"),
("explore","v","탐구하다, 탐색하다","B2"),
("classify","v","분류하다","B2"),
("categorize","v","범주화하다","B2"),
("compare","v","비교하다","B2"),
("contrast","v","대조하다","B2"),
("distinguish","v","구별하다","B2"),
("differentiate","v","구별하다, 차별화하다","B2"),
("summarize","v","요약하다","B2"),
("outline","v","개요를 서술하다","B2"),
("emphasize","v","강조하다","B2"),
("highlight","v","강조하다, 부각하다","B2"),
("clarify","v","명확히 하다","B2"),
("specify","v","명시하다","B2"),
("modify","v","수정하다, 변경하다","B2"),
("adjust","v","조정하다","B2"),
("adapt","v","적응하다, 각색하다","B2"),
("transform","v","변형하다, 완전히 바꾸다","B2"),
("convert","v","전환하다, 개조하다","B2"),
("generate","v","생성하다, 발생시키다","B2"),
("produce","v","생산하다, 야기하다","B2"),
("derive","v","도출하다, 유래하다","C1"),
("infer","v","추론하다","C1"),
("deduce","v","연역하다, 추론하다","C1"),
("imply","v","암시하다, 함축하다","B2"),
("conclude","v","결론짓다","B2"),
("hypothesize","v","가설을 세우다","C1"),
("postulate","v","가정하다, 상정하다","C2"),
("assume","v","가정하다, 추정하다","B2"),
("presume","v","추정하다","C1"),
("predict","v","예측하다","B2"),
("anticipate","v","예상하다","B2"),
("project","v","예상하다, 투사하다","B2"),
("propose","v","제안하다, 제기하다","B2"),
("suggest","v","제안하다, 시사하다","B2"),
("recommend","v","권고하다","B2"),
("advocate","v","옹호하다, 주장하다","C1"),
("assert","v","단언하다, 주장하다","C1"),
("claim","v","주장하다","B2"),
("contend","v","주장하다, 다투다","C1"),
("maintain","v","(주장을) 유지하다, 견지하다","B2"),
("argue","v","주장하다, 논증하다","B2"),
("reason","v","추론하다, 논리적으로 사고하다","B2"),
("justify","v","정당화하다","B2"),
("validate","v","입증하다, 유효화하다","C1"),
("verify","v","검증하다, 확인하다","C1"),
("confirm","v","확인하다, 확증하다","B2"),
("corroborate","v","확증하다, 뒷받침하다","C2"),
("substantiate","v","입증하다, 실증하다","C2"),
("refute","v","반박하다, 논박하다","C1"),
("rebut","v","반박하다","C2"),
("dispute","v","반박하다, 논쟁하다","B2"),
("challenge","v","이의를 제기하다","B2"),
("question","v","의문을 제기하다","B2"),
("undermine","v","약화시키다, 훼손하다","C1"),
("reconcile","v","조화시키다, 화해시키다","C1"),
("resolve","v","해결하다","B2"),
("address","v","다루다, 대처하다","B2"),
("tackle","v","다루다, 씨름하다","B2"),
("mitigate","v","완화하다, 경감하다","C1"),
("alleviate","v","완화하다","C1"),
("exacerbate","v","악화시키다","C2"),
("aggravate","v","악화시키다","C1"),
("facilitate","v","촉진하다, 용이하게 하다","C1"),
("enhance","v","향상시키다, 강화하다","B2"),
("augment","v","증대시키다","C2"),
("amplify","v","증폭시키다, 확대하다","C1"),
("diminish","v","줄어들다, 감소시키다","B2"),
("reduce","v","줄이다","B2"),
("minimize","v","최소화하다","B2"),
("maximize","v","최대화하다","B2"),
("optimize","v","최적화하다","C1"),
("accelerate","v","가속하다","B2"),
("hinder","v","방해하다, 저해하다","C1"),
("impede","v","방해하다, 지연시키다","C2"),
("inhibit","v","억제하다","C1"),
("constrain","v","제약하다","C1"),
("restrict","v","제한하다","B2"),
("confine","v","한정하다, 국한하다","C1"),
("regulate","v","규제하다, 조절하다","B2"),
("govern","v","지배하다, 규율하다","B2"),
("dominate","v","지배하다, 우세하다","B2"),
("prevail","v","우세하다, 만연하다","C1"),
("persist","v","지속되다, 고집하다","B2"),
("endure","v","지속되다, 견디다","B2"),
("sustain","v","지속하다, 떠받치다","B2"),
("maintain","v","유지하다","B2"),
("preserve","v","보존하다","B2"),
("conserve","v","보존하다, 아끼다","B2"),
("accumulate","v","축적하다","B2"),
("aggregate","v","집계하다, 합산하다","C1"),
("compile","v","편집하다, 집계하다","B2"),
("integrate","v","통합하다","B2"),
("incorporate","v","포함하다, 통합하다","B2"),
("synthesize","v","종합하다, 합성하다","C1"),
("consolidate","v","공고히 하다, 통합하다","C1"),
("comprise","v","구성하다, 이루다","C1"),
("constitute","v","구성하다, ~이 되다","C1"),
("compose","v","구성하다, 작성하다","B2"),
("encompass","v","포괄하다, 아우르다","C1"),
("entail","v","수반하다, 필요로 하다","C1"),
("involve","v","수반하다, 관련시키다","B2"),
("comprehend","v","이해하다, 파악하다","B2"),
("perceive","v","인지하다, 감지하다","B2"),
("conceive","v","구상하다, 상상하다","C1"),
("formulate","v","공식화하다, 표명하다","C1"),
("devise","v","고안하다","C1"),
("conceptualize","v","개념화하다","C2"),
("characterize","v","특징짓다","C1"),
("designate","v","지정하다, 명명하다","C1"),
("denote","v","나타내다, 의미하다","C1"),
("connote","v","함축하다","C2"),
("signify","v","의미하다, 나타내다","C1"),
("manifest","v","나타내다, 드러내다","C1"),
("exemplify","v","전형적으로 보여주다, 예시하다","C1"),
("epitomize","v","전형을 보여주다","C2"),
("embody","v","구현하다, 구체화하다","C1"),
("represent","v","나타내다, 대표하다","B2"),
("depict","v","묘사하다, 그리다","B2"),
("portray","v","묘사하다","B2"),
("convey","v","전달하다","B2"),
("articulate","v","분명히 표현하다","C1"),
("elaborate","v","상세히 설명하다","B2"),
("expound","v","상세히 설명하다","C2"),
("delineate","v","기술하다, 윤곽을 그리다","C2"),
("stipulate","v","규정하다, 명기하다","C2"),
("prescribe","v","규정하다, 처방하다","C1"),
("mandate","v","명령하다, 의무화하다","C1"),
("dictate","v","좌우하다, 지시하다","C1"),
("impose","v","부과하다, 강요하다","B2"),
("enforce","v","시행하다, 집행하다","B2"),
("implement","v","시행하다, 실행하다","B2"),
("execute","v","실행하다, 수행하다","B2"),
("undertake","v","착수하다, 떠맡다","B2"),
("initiate","v","개시하다, 착수하다","C1"),
("commence","v","시작하다","C1"),
("terminate","v","종료하다","C1"),
("cease","v","중단하다, 그치다","B2"),
("abolish","v","폐지하다","C1"),
("eliminate","v","제거하다","B2"),
("eradicate","v","근절하다","C2"),
("exclude","v","배제하다, 제외하다","B2"),
("preclude","v","막다, 배제하다","C2"),
("prohibit","v","금지하다","B2"),
("suppress","v","억압하다, 진압하다","C1"),
("displace","v","대체하다, 밀어내다","C1"),
("supplant","v","대체하다, 밀어내다","C2"),
("substitute","v","대체하다","B2"),
("supersede","v","대체하다, 대신하다","C2"),
("replace","v","대체하다","B2"),
("allocate","v","할당하다, 배분하다","B2"),
("distribute","v","분배하다, 배포하다","B2"),
("disseminate","v","퍼뜨리다, 전파하다","C2"),
("propagate","v","전파하다, 번식시키다","C2"),
("circulate","v","순환하다, 유포되다","B2"),
("transmit","v","전달하다, 전송하다","B2"),
("transfer","v","이전하다, 옮기다","B2"),
("exchange","v","교환하다","B2"),
("correlate","v","상관관계가 있다","C1"),
("associate","v","연관 짓다","B2"),
("attribute","v","~의 탓으로 돌리다","B2"),
("ascribe","v","~에 기인한 것으로 보다","C2"),
("assign","v","할당하다, 배정하다","B2"),
("designate","v","지정하다","C1"),
("estimate","v","추정하다","B2"),
("approximate","v","근사하다, 가깝다","C1"),
("quantify","v","수량화하다","C1"),
("calculate","v","계산하다","B2"),
("compute","v","계산하다, 산출하다","C1"),
("measure","v","측정하다","B2"),
("gauge","v","측정하다, 판단하다","C1"),
("monitor","v","감시하다, 관찰하다","B2"),
("track","v","추적하다","B2"),
("trace","v","추적하다, 거슬러 올라가다","B2"),
("detect","v","감지하다, 탐지하다","B2"),
("discern","v","분간하다, 식별하다","C2"),
("distinguish","v","구별하다","B2"),
("isolate","v","분리하다, 고립시키다","B2"),
("segregate","v","분리하다, 격리하다","C1"),
("extract","v","추출하다, 발췌하다","B2"),
("obtain","v","얻다, 획득하다","B2"),
("acquire","v","획득하다, 습득하다","B2"),
("attain","v","달성하다, 이루다","C1"),
("accomplish","v","성취하다","B2"),
("achieve","v","달성하다","B2"),
("fulfill","v","이행하다, 충족하다","B2"),
("satisfy","v","충족하다, 만족시키다","B2"),
("suffice","v","충분하다","C1"),
("exceed","v","초과하다, 능가하다","B2"),
("surpass","v","능가하다","C1"),
("outweigh","v","~보다 더 중요하다","C1"),
("prioritize","v","우선순위를 매기다","B2"),
("emphasize","v","강조하다","B2"),
("underscore","v","강조하다","C1"),
("reinforce","v","강화하다, 보강하다","B2"),
("bolster","v","강화하다, 북돋우다","C1"),
("strengthen","v","강화하다","B2"),
("fortify","v","강화하다","C1"),
("reflect","v","반영하다, 숙고하다","B2"),
("mirror","v","반영하다, 닮다","C1"),
("resemble","v","닮다, 유사하다","B2"),
("simulate","v","모의실험하다, 흉내내다","C1"),
("mimic","v","모방하다","C1"),
("replicate","v","복제하다, 재현하다","C1"),
("reproduce","v","재현하다, 번식하다","B2"),
("duplicate","v","복제하다","B2"),
("emerge","v","나타나다, 부상하다","B2"),
("arise","v","발생하다, 생기다","B2"),
("originate","v","비롯되다, 유래하다","B2"),
("stem","v","기인하다, 유래하다","C1"),
("evolve","v","진화하다, 발전하다","B2"),
("develop","v","발전하다, 개발하다","B2"),
("mature","v","성숙하다","B2"),
("flourish","v","번성하다","C1"),
("thrive","v","번창하다, 잘 자라다","B2"),
("proliferate","v","급증하다, 확산하다","C2"),
("expand","v","확장하다","B2"),
("extend","v","확장하다, 연장하다","B2"),
("broaden","v","넓히다","B2"),
("contract","v","수축하다, 계약하다","B2"),
("compress","v","압축하다","C1"),
("condense","v","응축하다, 요약하다","C1"),
("fluctuate","v","변동하다","C1"),
("vary","v","다양하다, 변화하다","B2"),
("deviate","v","벗어나다, 일탈하다","C1"),
("diverge","v","갈라지다, 벗어나다","C1"),
("converge","v","수렴하다, 모이다","C1"),
("coincide","v","일치하다, 동시에 일어나다","C1"),
("correspond","v","일치하다, 상응하다","B2"),
("conform","v","순응하다, 따르다","C1"),
("comply","v","준수하다, 따르다","B2"),
("adhere","v","고수하다, 준수하다","C1"),
("abide","v","따르다, 준수하다","C1"),
("violate","v","위반하다","B2"),
("breach","v","위반하다, 어기다","C1"),
("contravene","v","위반하다, 저촉되다","C2"),
("transgress","v","위반하다, 넘어서다","C2"),
("compensate","v","보상하다, 상쇄하다","B2"),
("offset","v","상쇄하다","C1"),
("counteract","v","대응하다, 중화하다","C1"),
("neutralize","v","무효화하다, 중화하다","C1"),
("nullify","v","무효화하다","C2"),
("negate","v","부정하다, 무효화하다","C2"),
("contradict","v","모순되다, 반박하다","B2"),
("oppose","v","반대하다","B2"),
("resist","v","저항하다","B2"),
("counter","v","반박하다, 대응하다","B2"),
("suppress","v","억압하다","C1"),
("provoke","v","유발하다, 자극하다","B2"),
("trigger","v","유발하다, 촉발하다","B2"),
("induce","v","유도하다, 유발하다","C1"),
("elicit","v","이끌어내다","C2"),
("evoke","v","불러일으키다","C1"),
("stimulate","v","자극하다, 촉진하다","B2"),
("prompt","v","촉발하다, 유도하다","B2"),
("incite","v","선동하다, 자극하다","C2"),
("instigate","v","선동하다, 유발하다","C2"),
("foster","v","조성하다, 육성하다","C1"),
("cultivate","v","기르다, 함양하다","C1"),
("nurture","v","양육하다, 키우다","C1"),
("promote","v","촉진하다, 장려하다","B2"),
("encourage","v","장려하다, 촉진하다","B2"),
("discourage","v","단념시키다, 저해하다","B2"),
("deter","v","단념시키다, 억제하다","C1"),
("dissuade","v","단념시키다","C2"),
("compel","v","강요하다, ~하게 만들다","C1"),
("coerce","v","강압하다","C2"),
("oblige","v","의무를 지우다, 강요하다","B2"),
("necessitate","v","필요로 하다","C2"),
("warrant","v","정당화하다, 필요로 하다","C1"),
("merit","v","~할 만하다","C1"),
("deserve","v","~을 받을 만하다","B2"),
("entitle","v","자격을 주다","C1"),
("empower","v","권한을 주다","C1"),
("enable","v","가능하게 하다","B2"),
("permit","v","허용하다","B2"),
("authorize","v","권한을 부여하다, 인가하다","C1"),
("sanction","v","승인하다, 제재하다","C1"),
("endorse","v","지지하다, 승인하다","C1"),
("ratify","v","비준하다, 승인하다","C2"),
("approve","v","승인하다","B2"),
("acknowledge","v","인정하다, 시인하다","B2"),
("concede","v","인정하다, 양보하다","C1"),
("admit","v","인정하다","B2"),
("recognize","v","인정하다, 알아보다","B2"),
("appreciate","v","진가를 알다, 인식하다","B2"),
("discard","v","버리다, 폐기하다","B2"),
("abandon","v","버리다, 포기하다","B2"),
("relinquish","v","포기하다, 내주다","C2"),
("forgo","v","포기하다, 삼가다","C2"),
("renounce","v","포기하다, 단념하다","C2"),
("retain","v","유지하다, 보유하다","B2"),
("retrieve","v","되찾다, 검색하다","B2"),
("recover","v","회복하다, 되찾다","B2"),
("restore","v","복원하다, 회복하다","B2"),
("revive","v","되살리다, 부활시키다","C1"),
("renew","v","갱신하다, 재개하다","B2"),
("reiterate","v","반복하다, 되풀이하다","C1"),
("recapitulate","v","요약하다, 되풀이하다","C2"),
("rephrase","v","바꿔 말하다","C1"),
("paraphrase","v","바꿔 표현하다","C1"),
("annotate","v","주석을 달다","C2"),
("cite","v","인용하다","B2"),
("quote","v","인용하다","B2"),
("reference","v","참조하다, 언급하다","B2"),
("allude","v","넌지시 언급하다","C2"),
("attest","v","증명하다, 입증하다","C2"),
("testify","v","증언하다","C1"),
("vindicate","v","정당성을 입증하다","C2"),
("exonerate","v","혐의를 벗기다","C2"),
("scrutinize","v","면밀히 조사하다","C1"),
("probe","v","면밀히 조사하다, 탐구하다","C1"),
("dissect","v","해부하다, 상세히 분석하다","C1"),
("survey","v","조사하다, 개관하다","B2"),
("inspect","v","점검하다, 검사하다","B2"),
("audit","v","감사하다, 회계 검토하다","C1"),
("review","v","검토하다, 논평하다","B2"),
("revise","v","수정하다, 개정하다","B2"),
("amend","v","개정하다, 수정하다","C1"),
("rectify","v","바로잡다, 시정하다","C2"),
("remedy","v","바로잡다, 개선하다","C1"),
("refine","v","정제하다, 개선하다","C1"),
("streamline","v","간소화하다, 능률화하다","C1"),
("standardize","v","표준화하다","C1"),
("systematize","v","체계화하다","C2"),
("organize","v","조직하다, 정리하다","B2"),
("coordinate","v","조율하다, 조정하다","B2"),
("orchestrate","v","조율하다, 총괄하다","C2"),
("administer","v","관리하다, 시행하다","C1"),
("oversee","v","감독하다","C1"),
("supervise","v","감독하다","B2"),
("delegate","v","위임하다","C1"),
("designate","v","지정하다, 임명하다","C1"),
("nominate","v","지명하다, 추천하다","B2"),
("appoint","v","임명하다","B2"),
("elect","v","선출하다, 선택하다","B2"),
("elicit","v","이끌어내다","C2"),
("solicit","v","요청하다, 간청하다","C2"),
("procure","v","조달하다, 입수하다","C2"),
("furnish","v","제공하다, 갖추다","C1"),
("supply","v","공급하다","B2"),
("provide","v","제공하다","B2"),
("render","v","(어떤 상태로) 만들다, 표현하다","C1"),
("yield","v","산출하다, 양보하다","B2"),
("generate","v","생성하다","B2"),
("engender","v","야기하다, 낳다","C2"),
("precipitate","v","촉발하다, 재촉하다","C2"),
("culminate","v","정점에 이르다","C1"),
("consummate","v","완성하다, 완결하다","C2"),
("finalize","v","마무리하다","B2"),
("conclude","v","결론짓다, 마무리하다","B2"),

# ---- Abstract nouns ----
("hypothesis","n","가설","B2"),
("theory","n","이론","B2"),
("thesis","n","논제, 학위논문","B2"),
("premise","n","전제","C1"),
("assumption","n","가정, 전제","B2"),
("presumption","n","추정, 가정","C1"),
("proposition","n","명제, 제안","C1"),
("postulate","n","공준, 가정","C2"),
("axiom","n","공리, 자명한 이치","C2"),
("principle","n","원리, 원칙","B2"),
("doctrine","n","교리, 학설","C1"),
("tenet","n","교의, 신조","C2"),
("paradigm","n","패러다임, 전형","C1"),
("framework","n","틀, 체계","B2"),
("model","n","모형, 모델","B2"),
("construct","n","구성 개념","C1"),
("concept","n","개념","B2"),
("conception","n","개념, 구상","C1"),
("notion","n","관념, 개념","B2"),
("abstraction","n","추상, 추상적 개념","C1"),
("criterion","n","기준, 척도","B2"),
("benchmark","n","기준, 지표","C1"),
("standard","n","기준, 표준","B2"),
("norm","n","규범, 표준","C1"),
("parameter","n","매개변수, 한도","C1"),
("variable","n","변수","B2"),
("constant","n","상수","B2"),
("factor","n","요인, 인자","B2"),
("determinant","n","결정 요인","C2"),
("component","n","구성 요소","B2"),
("element","n","요소, 성분","B2"),
("constituent","n","구성 요소","C1"),
("aspect","n","측면","B2"),
("dimension","n","차원, 측면","B2"),
("attribute","n","속성, 특성","B2"),
("property","n","속성, 특성","B2"),
("characteristic","n","특징, 특성","B2"),
("trait","n","특성, 형질","B2"),
("feature","n","특징","B2"),
("quality","n","특질, 자질","B2"),
("nature","n","본질, 성질","B2"),
("essence","n","본질, 핵심","C1"),
("substance","n","본질, 실체","B2"),
("core","n","핵심","B2"),
("crux","n","핵심, 관건","C2"),
("gist","n","요지, 골자","C1"),
("premise","n","전제","C1"),
("rationale","n","근거, 이론적 설명","C1"),
("basis","n","근거, 기반","B2"),
("foundation","n","기초, 토대","B2"),
("ground","n","근거, 기반","B2"),
("justification","n","정당화, 근거","B2"),
("grounds","n","근거, 이유","B2"),
("warrant","n","근거, 정당성","C1"),
("premise","n","전제","C1"),
("evidence","n","증거","B2"),
("proof","n","증거, 증명","B2"),
("testimony","n","증언, 증거","C1"),
("corroboration","n","확증, 뒷받침","C2"),
("verification","n","검증, 확인","C1"),
("validation","n","입증, 유효성 확인","C1"),
("confirmation","n","확인, 확증","B2"),
("refutation","n","반박, 논박","C2"),
("rebuttal","n","반박","C2"),
("objection","n","반대, 이의","B2"),
("counterargument","n","반론","C1"),
("argument","n","논거, 주장","B2"),
("reasoning","n","추론, 논리","B2"),
("logic","n","논리","B2"),
("inference","n","추론","C1"),
("deduction","n","연역, 추론","C1"),
("induction","n","귀납","C1"),
("implication","n","함의, 영향","B2"),
("consequence","n","결과, 귀결","B2"),
("ramification","n","파급 효과, 영향","C2"),
("outcome","n","결과","B2"),
("result","n","결과","B2"),
("finding","n","연구 결과, 발견","B2"),
("conclusion","n","결론","B2"),
("verdict","n","판정, 평결","C1"),
("assessment","n","평가","B2"),
("evaluation","n","평가","B2"),
("appraisal","n","평가, 감정","C1"),
("analysis","n","분석","B2"),
("synthesis","n","종합, 합성","C1"),
("interpretation","n","해석","B2"),
("perspective","n","관점, 시각","B2"),
("viewpoint","n","관점","B2"),
("standpoint","n","견지, 관점","C1"),
("stance","n","입장, 태도","C1"),
("position","n","입장, 견해","B2"),
("orientation","n","방향, 성향","B2"),
("approach","n","접근법","B2"),
("methodology","n","방법론","C1"),
("method","n","방법","B2"),
("technique","n","기법, 기술","B2"),
("procedure","n","절차","B2"),
("protocol","n","규약, 절차","C1"),
("mechanism","n","기제, 메커니즘","B2"),
("process","n","과정","B2"),
("phenomenon","n","현상","B2"),
("occurrence","n","발생, 사건","C1"),
("incidence","n","발생률, 발생 정도","C1"),
("prevalence","n","유병률, 만연","C1"),
("frequency","n","빈도, 주파수","B2"),
("magnitude","n","규모, 중요도","C1"),
("scale","n","규모, 척도","B2"),
("scope","n","범위","B2"),
("extent","n","정도, 범위","B2"),
("spectrum","n","범위, 스펙트럼","C1"),
("range","n","범위","B2"),
("continuum","n","연속체","C2"),
("proportion","n","비율, 부분","B2"),
("ratio","n","비율","B2"),
("percentage","n","백분율","B2"),
("fraction","n","일부, 분수","B2"),
("quantity","n","양, 수량","B2"),
("magnitude","n","규모","C1"),
("volume","n","양, 부피","B2"),
("threshold","n","문턱, 한계점","C1"),
("limit","n","한계","B2"),
("boundary","n","경계","B2"),
("constraint","n","제약","C1"),
("restriction","n","제한","B2"),
("limitation","n","한계, 제약","B2"),
("condition","n","조건, 상태","B2"),
("prerequisite","n","전제 조건, 필수 요건","C1"),
("requirement","n","요건, 필요조건","B2"),
("provision","n","조항, 준비","C1"),
("stipulation","n","규정, 조건","C2"),
("clause","n","조항, 절","C1"),
("criterion","n","기준","B2"),
("indicator","n","지표","B2"),
("index","n","지수, 색인","B2"),
("metric","n","측정 기준, 지표","C1"),
("measure","n","척도, 조치","B2"),
("gauge","n","척도, 기준","C1"),
("correlation","n","상관관계","C1"),
("association","n","연관성, 연상","B2"),
("relationship","n","관계","B2"),
("relation","n","관계, 관련","B2"),
("connection","n","연관, 연결","B2"),
("linkage","n","연결, 연관","C1"),
("interdependence","n","상호 의존","C2"),
("interaction","n","상호작용","B2"),
("interplay","n","상호작용","C1"),
("dynamics","n","역학, 역동성","C1"),
("equilibrium","n","평형, 균형","C1"),
("balance","n","균형","B2"),
("stability","n","안정성","B2"),
("volatility","n","변동성, 불안정성","C2"),
("variability","n","가변성","C1"),
("variation","n","변이, 변화","B2"),
("fluctuation","n","변동","C1"),
("deviation","n","일탈, 편차","C1"),
("discrepancy","n","불일치, 차이","C1"),
("disparity","n","격차, 불균형","C1"),
("inequality","n","불평등","B2"),
("divergence","n","차이, 분기","C2"),
("convergence","n","수렴, 집중","C2"),
("consistency","n","일관성","B2"),
("coherence","n","일관성, 통일성","C1"),
("uniformity","n","균일성","C1"),
("homogeneity","n","동질성","C2"),
("heterogeneity","n","이질성","C2"),
("diversity","n","다양성","B2"),
("complexity","n","복잡성","B2"),
("simplicity","n","단순성","B2"),
("ambiguity","n","모호성","C1"),
("uncertainty","n","불확실성","B2"),
("probability","n","확률, 개연성","B2"),
("likelihood","n","가능성","B2"),
("tendency","n","경향","B2"),
("propensity","n","성향, 경향","C2"),
("inclination","n","경향, 성향","C1"),
("predisposition","n","기질, 성향","C2"),
("bias","n","편향, 편견","B2"),
("prejudice","n","편견","B2"),
("subjectivity","n","주관성","C1"),
("objectivity","n","객관성","C1"),
("validity","n","타당성","C1"),
("reliability","n","신뢰성","B2"),
("credibility","n","신빙성, 신뢰성","C1"),
("plausibility","n","그럴듯함, 타당성","C2"),
("feasibility","n","실현 가능성","C1"),
("viability","n","실행 가능성, 생존력","C1"),
("applicability","n","적용 가능성","C1"),
("relevance","n","관련성, 적절성","B2"),
("significance","n","중요성, 의의","B2"),
("importance","n","중요성","B2"),
("priority","n","우선순위","B2"),
("emphasis","n","강조","B2"),
("prominence","n","두드러짐, 명성","C1"),
("salience","n","현저성, 두드러짐","C2"),
("implication","n","함의","B2"),
("connotation","n","함축, 내포","C2"),
("denotation","n","외연, 명시적 의미","C2"),
("nuance","n","미묘한 차이, 뉘앙스","C1"),
("subtlety","n","미묘함","C1"),
("distinction","n","구별, 차이","B2"),
("differentiation","n","차별화, 구별","C1"),
("categorization","n","범주화, 분류","C1"),
("classification","n","분류","B2"),
("taxonomy","n","분류 체계","C2"),
("hierarchy","n","위계, 서열","C1"),
("structure","n","구조","B2"),
("configuration","n","배치, 구성","C1"),
("composition","n","구성, 성분","B2"),
("arrangement","n","배열, 배치","B2"),
("organization","n","조직, 구성","B2"),
("system","n","체계, 시스템","B2"),
("network","n","연결망, 네트워크","B2"),
("infrastructure","n","기반 시설","B2"),
("apparatus","n","장치, 기구","C1"),
("instrument","n","도구, 수단","B2"),
("medium","n","매체, 수단","B2"),
("vehicle","n","수단, 매개체","B2"),
("means","n","수단","B2"),
("device","n","장치, 방책","B2"),
("tool","n","도구","B2"),
("resource","n","자원","B2"),
("asset","n","자산","B2"),
("commodity","n","상품, 필수품","C1"),
("capital","n","자본","B2"),
("expenditure","n","지출, 비용","C1"),
("allocation","n","할당, 배분","C1"),
("distribution","n","분배, 분포","B2"),
("acquisition","n","획득, 습득","B2"),
("accumulation","n","축적","C1"),
("aggregation","n","집합, 집계","C2"),
("consolidation","n","통합, 강화","C1"),
("integration","n","통합","B2"),
("incorporation","n","통합, 편입","C1"),
("expansion","n","확장, 팽창","B2"),
("contraction","n","수축, 축소","C1"),
("proliferation","n","급증, 확산","C2"),
("emergence","n","출현, 대두","C1"),
("evolution","n","진화, 발전","B2"),
("progression","n","진행, 발전","C1"),
("transition","n","전환, 이행","B2"),
("transformation","n","변형, 변화","B2"),
("transition","n","전환","B2"),
("shift","n","변화, 이동","B2"),
("displacement","n","이동, 대체","C1"),
("succession","n","연속, 계승","C1"),
("sequence","n","순서, 연속","B2"),
("continuity","n","연속성","C1"),
("duration","n","지속 기간","B2"),
("interval","n","간격","B2"),
("phase","n","단계, 국면","B2"),
("stage","n","단계","B2"),
("cycle","n","순환, 주기","B2"),
("recurrence","n","재발, 반복","C1"),
("repetition","n","반복","B2"),
("iteration","n","반복, 되풀이","C1"),
("instance","n","사례, 경우","B2"),
("case","n","사례, 경우","B2"),
("scenario","n","시나리오, 상황","B2"),
("circumstance","n","상황, 정황","B2"),
("context","n","맥락, 상황","B2"),
("setting","n","환경, 배경","B2"),
("environment","n","환경","B2"),
("domain","n","영역, 분야","C1"),
("realm","n","영역, 범위","C1"),
("sphere","n","영역, 분야","C1"),
("field","n","분야","B2"),
("discipline","n","학문 분야, 규율","B2"),
("arena","n","영역, 무대","C1"),
("premise","n","전제","C1"),
("objective","n","목표","B2"),
("aim","n","목표","B2"),
("goal","n","목표","B2"),
("purpose","n","목적","B2"),
("intention","n","의도","B2"),
("motive","n","동기","B2"),
("motivation","n","동기 부여","B2"),
("incentive","n","유인, 동기","B2"),
("impetus","n","자극, 추진력","C2"),
("stimulus","n","자극, 유인","C1"),
("catalyst","n","촉매, 기폭제","C1"),
("driver","n","추진 요인, 동인","B2"),
("trigger","n","계기, 유발 요인","B2"),
("cause","n","원인","B2"),
("origin","n","기원, 근원","B2"),
("source","n","원천, 출처","B2"),
("root","n","근원, 뿌리","B2"),
("antecedent","n","선행 사건, 선례","C2"),
("precedent","n","선례, 전례","C1"),
("prototype","n","원형, 시제품","C1"),
("archetype","n","원형, 전형","C2"),
("template","n","견본, 틀","B2"),
("blueprint","n","청사진, 설계도","C1"),
("scheme","n","계획, 책략","B2"),
("strategy","n","전략","B2"),
("tactic","n","전술, 방책","B2"),
("policy","n","정책, 방침","B2"),
("initiative","n","계획, 주도권","B2"),
("agenda","n","의제, 안건","B2"),
("mandate","n","권한, 명령","C1"),
("directive","n","지시, 지령","C1"),
("regulation","n","규정, 규제","B2"),
("legislation","n","법률, 입법","B2"),
("statute","n","법령, 법규","C1"),
("ordinance","n","조례, 법령","C2"),
("convention","n","관습, 협약","B2"),
("custom","n","관습","B2"),
("practice","n","관행, 실행","B2"),
("procedure","n","절차","B2"),
("protocol","n","규약","C1"),
("norm","n","규범","C1"),
("etiquette","n","예법, 관례","C1"),
("consensus","n","합의, 의견 일치","C1"),
("agreement","n","합의, 동의","B2"),
("accord","n","합의, 일치","C1"),
("compromise","n","타협","B2"),
("concession","n","양보","C1"),
("reconciliation","n","화해, 조화","C1"),
("resolution","n","해결, 결의","B2"),
("settlement","n","해결, 합의","B2"),
("controversy","n","논쟁","B2"),
("dispute","n","분쟁, 논쟁","B2"),
("debate","n","토론, 논쟁","B2"),
("discourse","n","담론, 담화","C1"),
("dialogue","n","대화","B2"),
("rhetoric","n","수사, 미사여구","C1"),
("narrative","n","서사, 이야기","B2"),
("account","n","설명, 기술","B2"),
("depiction","n","묘사","C1"),
("portrayal","n","묘사","C1"),
("representation","n","표현, 대표","B2"),
("illustration","n","예시, 삽화","B2"),
("exemplification","n","예시","C2"),
("demonstration","n","입증, 시연","B2"),
("manifestation","n","징후, 발현","C1"),
("expression","n","표현","B2"),
("articulation","n","명확한 표현","C2"),
("formulation","n","공식화, 표현","C1"),
("statement","n","진술, 서술","B2"),
("assertion","n","단언, 주장","C1"),
("claim","n","주장","B2"),
("contention","n","주장, 논쟁","C1"),
("declaration","n","선언, 진술","B2"),
("proclamation","n","선언, 공표","C2"),
("premise","n","전제","C1"),
("observation","n","관찰, 논평","B2"),
("remark","n","논평, 발언","B2"),
("commentary","n","논평, 해설","C1"),
("critique","n","비평, 평론","C1"),
("criticism","n","비판, 비평","B2"),
("appraisal","n","평가","C1"),
("insight","n","통찰, 이해","B2"),
("understanding","n","이해","B2"),
("comprehension","n","이해력","B2"),
("cognition","n","인지, 인식","C1"),
("awareness","n","인식, 자각","B2"),
("perception","n","지각, 인식","B2"),
("conception","n","개념, 이해","C1"),
("intuition","n","직관","C1"),
("insight","n","통찰력","B2"),
("wisdom","n","지혜","B2"),
("knowledge","n","지식","B2"),
("expertise","n","전문 지식","B2"),
("competence","n","역량, 능력","B2"),
("proficiency","n","숙달, 능숙함","C1"),
("aptitude","n","적성, 소질","C1"),
("capacity","n","능력, 수용력","B2"),
("capability","n","능력, 역량","B2"),
("faculty","n","능력, 학부","C1"),
("potential","n","잠재력","B2"),
("propensity","n","성향","C2"),
("disposition","n","성향, 기질","C1"),
("temperament","n","기질, 성미","C1"),
("mentality","n","사고방식","C1"),
("mindset","n","사고방식","B2"),
("outlook","n","관점, 전망","B2"),
("attitude","n","태도","B2"),
("sentiment","n","정서, 감정","C1"),
("morale","n","사기, 의욕","C1"),
("motivation","n","동기","B2"),
("aspiration","n","열망, 포부","C1"),
("ambition","n","야망, 포부","B2"),
("endeavor","n","노력, 시도","C1"),
("undertaking","n","일, 사업","C1"),
("venture","n","모험적 사업","B2"),
("enterprise","n","기업, 사업","B2"),
("pursuit","n","추구, 활동","B2"),
("quest","n","탐구, 추구","C1"),
("inquiry","n","탐구, 조사","B2"),
("investigation","n","조사, 수사","B2"),
("examination","n","조사, 검토","B2"),
("exploration","n","탐구, 탐험","B2"),
("experiment","n","실험","B2"),
("trial","n","시험, 실험","B2"),
("observation","n","관찰","B2"),
("survey","n","조사, 설문","B2"),
("census","n","인구조사","C1"),
("sample","n","표본, 견본","B2"),
("specimen","n","표본, 견본","C1"),
("subset","n","부분집합","C1"),
("category","n","범주","B2"),
("classification","n","분류","B2"),
("cluster","n","무리, 집단","B2"),
("array","n","배열, 집합","C1"),
("compilation","n","편집물, 모음","C1"),
("collection","n","수집, 모음","B2"),
("corpus","n","말뭉치, 자료 전체","C2"),
("archive","n","기록 보관소, 자료","C1"),
("repository","n","저장소, 보고","C2"),
("database","n","데이터베이스","B2"),
("dataset","n","데이터 집합","C1"),
("statistic","n","통계치","B2"),
("figure","n","수치, 그림","B2"),
("datum","n","자료, 데이터","C1"),
("estimate","n","추정치","B2"),
("projection","n","예상, 추정","B2"),
("forecast","n","예측, 전망","B2"),
("prediction","n","예측","B2"),
("prognosis","n","예후, 예측","C2"),
("anticipation","n","예상, 기대","C1"),
("expectation","n","기대, 예상","B2"),
("premise","n","전제","C1"),
("supposition","n","추측, 가정","C2"),
("speculation","n","추측, 사색","C1"),
("conjecture","n","추측, 억측","C2"),
("hypothesis","n","가설","B2"),
("guess","n","추측","B2"),
("estimation","n","추정, 평가","B2"),
("approximation","n","근사치","C1"),
("calculation","n","계산","B2"),
("computation","n","계산, 연산","C1"),
("quantification","n","수량화","C2"),
("enumeration","n","열거, 계산","C2"),
("tabulation","n","도표화, 집계","C2"),

# ---- Academic adjectives ----
("empirical","adj","경험적인, 실증적인","C1"),
("theoretical","adj","이론적인","B2"),
("conceptual","adj","개념적인","C1"),
("abstract","adj","추상적인","B2"),
("concrete","adj","구체적인","B2"),
("tangible","adj","유형의, 실체가 있는","C1"),
("intangible","adj","무형의","C1"),
("hypothetical","adj","가설의, 가정의","C1"),
("speculative","adj","사색적인, 추측의","C1"),
("provisional","adj","잠정적인","C1"),
("tentative","adj","잠정적인, 시험적인","C1"),
("preliminary","adj","예비의, 사전의","B2"),
("subsequent","adj","이후의, 후속의","B2"),
("prior","adj","이전의, 우선하는","B2"),
("antecedent","adj","선행하는","C2"),
("ensuing","adj","뒤이은, 계속되는","C2"),
("consequent","adj","결과로 생기는","C1"),
("concurrent","adj","동시에 일어나는","C1"),
("simultaneous","adj","동시의","B2"),
("successive","adj","연속적인","C1"),
("consecutive","adj","연속적인","B2"),
("cumulative","adj","누적되는","C1"),
("incremental","adj","점진적인, 증가하는","C2"),
("gradual","adj","점진적인","B2"),
("progressive","adj","점진적인, 진보적인","B2"),
("marginal","adj","미미한, 주변의","C1"),
("negligible","adj","무시해도 될, 하찮은","C1"),
("substantial","adj","상당한, 실질적인","B2"),
("considerable","adj","상당한","B2"),
("significant","adj","중요한, 상당한","B2"),
("notable","adj","주목할 만한","B2"),
("remarkable","adj","놀랄 만한, 주목할 만한","B2"),
("prominent","adj","두드러진, 저명한","B2"),
("salient","adj","현저한, 두드러진","C2"),
("conspicuous","adj","눈에 띄는","C1"),
("pronounced","adj","뚜렷한, 명백한","C1"),
("distinct","adj","뚜렷한, 별개의","B2"),
("distinctive","adj","독특한, 특유의","B2"),
("characteristic","adj","특유의, 전형적인","B2"),
("representative","adj","대표적인","B2"),
("typical","adj","전형적인","B2"),
("prototypical","adj","전형적인, 원형의","C2"),
("archetypal","adj","전형적인","C2"),
("exemplary","adj","모범적인, 본보기가 되는","C1"),
("generic","adj","일반적인, 포괄적인","C1"),
("universal","adj","보편적인","B2"),
("prevalent","adj","널리 퍼진, 만연한","C1"),
("pervasive","adj","만연한, 스며드는","C2"),
("ubiquitous","adj","도처에 있는, 편재하는","C2"),
("widespread","adj","광범위한, 널리 퍼진","B2"),
("rampant","adj","만연한, 걷잡을 수 없는","C2"),
("endemic","adj","고유의, 풍토성의","C2"),
("inherent","adj","내재하는, 고유의","C1"),
("intrinsic","adj","본질적인, 고유의","C1"),
("innate","adj","선천적인, 타고난","C1"),
("inborn","adj","타고난","C1"),
("congenital","adj","선천적인","C2"),
("fundamental","adj","근본적인","B2"),
("elemental","adj","기본적인, 근원적인","C2"),
("essential","adj","필수적인, 본질적인","B2"),
("integral","adj","필수적인, 통합적인","C1"),
("indispensable","adj","없어서는 안 될","C1"),
("vital","adj","필수적인, 중대한","B2"),
("crucial","adj","결정적인, 중대한","B2"),
("pivotal","adj","중추적인, 중요한","C1"),
("critical","adj","중대한, 비판적인","B2"),
("paramount","adj","가장 중요한, 최고의","C2"),
("preeminent","adj","탁월한, 우수한","C2"),
("predominant","adj","지배적인, 우세한","C1"),
("dominant","adj","지배적인, 우세한","B2"),
("prevailing","adj","우세한, 지배적인","C1"),
("overriding","adj","가장 중요한, 최우선의","C2"),
("secondary","adj","부차적인, 이차적인","B2"),
("subordinate","adj","종속적인, 하위의","C1"),
("subsidiary","adj","부차적인, 종속의","C1"),
("ancillary","adj","보조적인, 부수적인","C2"),
("auxiliary","adj","보조의","C1"),
("supplementary","adj","보충의, 추가의","C1"),
("complementary","adj","상호 보완적인","C1"),
("mutual","adj","상호간의","B2"),
("reciprocal","adj","상호간의, 호혜적인","C2"),
("interdependent","adj","상호 의존적인","C1"),
("interrelated","adj","서로 관련된","C1"),
("interconnected","adj","상호 연결된","C1"),
("correlated","adj","상관관계가 있는","C1"),
("relative","adj","상대적인","B2"),
("absolute","adj","절대적인","B2"),
("proportional","adj","비례하는","C1"),
("proportionate","adj","균형 잡힌, 비례하는","C2"),
("comparative","adj","비교의, 상대적인","B2"),
("respective","adj","각각의","B2"),
("collective","adj","집단적인, 공동의","B2"),
("aggregate","adj","총계의, 집합적인","C1"),
("cumulative","adj","누적적인","C1"),
("comprehensive","adj","포괄적인, 종합적인","B2"),
("exhaustive","adj","철저한, 완전한","C1"),
("thorough","adj","철저한","B2"),
("meticulous","adj","꼼꼼한, 세심한","C1"),
("rigorous","adj","엄격한, 철저한","C1"),
("stringent","adj","엄격한","C2"),
("scrupulous","adj","꼼꼼한, 양심적인","C2"),
("precise","adj","정밀한, 정확한","B2"),
("accurate","adj","정확한","B2"),
("explicit","adj","명시적인, 분명한","C1"),
("implicit","adj","암시적인, 내재된","C1"),
("overt","adj","명백한, 공공연한","C2"),
("covert","adj","은밀한, 비밀의","C2"),
("tacit","adj","암묵적인","C2"),
("unequivocal","adj","명백한, 모호하지 않은","C2"),
("unambiguous","adj","명확한","C1"),
("ambiguous","adj","모호한","C1"),
("equivocal","adj","모호한, 애매한","C2"),
("vague","adj","모호한, 막연한","B2"),
("obscure","adj","불분명한, 잘 알려지지 않은","C1"),
("nebulous","adj","모호한, 흐릿한","C2"),
("elusive","adj","파악하기 어려운","C2"),
("subtle","adj","미묘한","B2"),
("nuanced","adj","미묘한 차이가 있는","C2"),
("coherent","adj","일관된, 논리 정연한","C1"),
("cohesive","adj","응집력 있는, 결합된","C1"),
("consistent","adj","일관된","B2"),
("systematic","adj","체계적인","B2"),
("methodical","adj","체계적인, 꼼꼼한","C1"),
("logical","adj","논리적인","B2"),
("rational","adj","합리적인, 이성적인","B2"),
("coherent","adj","조리 있는","C1"),
("valid","adj","타당한, 유효한","B2"),
("sound","adj","타당한, 건전한","B2"),
("cogent","adj","설득력 있는","C2"),
("compelling","adj","설득력 있는, 강력한","C1"),
("persuasive","adj","설득력 있는","B2"),
("convincing","adj","설득력 있는","B2"),
("plausible","adj","그럴듯한, 타당한","C1"),
("credible","adj","신뢰할 수 있는","C1"),
("tenable","adj","옹호할 수 있는, 유지 가능한","C2"),
("defensible","adj","방어 가능한, 정당한","C2"),
("justifiable","adj","정당한, 타당한","C1"),
("legitimate","adj","정당한, 합법적인","B2"),
("warranted","adj","정당한, 근거 있는","C1"),
("unfounded","adj","근거 없는","C1"),
("unsubstantiated","adj","입증되지 않은","C2"),
("baseless","adj","근거 없는","C1"),
("spurious","adj","가짜의, 그럴듯한","C2"),
("fallacious","adj","잘못된, 오류의","C2"),
("erroneous","adj","잘못된","C1"),
("flawed","adj","결함이 있는","B2"),
("dubious","adj","의심스러운","C1"),
("questionable","adj","의심스러운","B2"),
("debatable","adj","논쟁의 여지가 있는","C1"),
("contentious","adj","논쟁을 일으키는","C2"),
("controversial","adj","논란이 많은","B2"),
("disputed","adj","논쟁 중인","B2"),
("contested","adj","논쟁이 되는","C1"),
("conclusive","adj","결정적인, 확실한","C1"),
("definitive","adj","확정적인, 결정적인","C1"),
("decisive","adj","결정적인","B2"),
("inconclusive","adj","결론이 나지 않은","C1"),
("indeterminate","adj","불확정적인","C2"),
("arbitrary","adj","임의적인, 자의적인","C1"),
("random","adj","무작위의","B2"),
("systematic","adj","체계적인","B2"),
("deliberate","adj","의도적인, 신중한","B2"),
("intentional","adj","의도적인","B2"),
("inadvertent","adj","의도치 않은, 부주의한","C2"),
("incidental","adj","부수적인, 우연한","C1"),
("coincidental","adj","우연의","C1"),
("spontaneous","adj","자발적인, 즉흥적인","B2"),
("inevitable","adj","불가피한","B2"),
("unavoidable","adj","피할 수 없는","B2"),
("imperative","adj","반드시 해야 하는, 긴요한","C1"),
("mandatory","adj","의무적인","B2"),
("obligatory","adj","의무적인","C1"),
("compulsory","adj","강제적인, 의무적인","B2"),
("optional","adj","선택적인","B2"),
("voluntary","adj","자발적인","B2"),
("discretionary","adj","재량에 따른","C2"),
("conditional","adj","조건부의","B2"),
("contingent","adj","~에 달린, 부수적인","C2"),
("dependent","adj","의존적인","B2"),
("independent","adj","독립적인","B2"),
("autonomous","adj","자율적인, 독립된","C1"),
("self-sufficient","adj","자급자족하는","C1"),
("viable","adj","실행 가능한, 생존 가능한","C1"),
("feasible","adj","실현 가능한","C1"),
("practicable","adj","실행 가능한","C2"),
("attainable","adj","달성 가능한","C1"),
("achievable","adj","성취 가능한","B2"),
("applicable","adj","적용 가능한, 해당하는","B2"),
("pertinent","adj","적절한, 관련 있는","C1"),
("relevant","adj","관련 있는, 적절한","B2"),
("germane","adj","적절한, 밀접한","C2"),
("apposite","adj","적절한","C2"),
("appropriate","adj","적절한","B2"),
("suitable","adj","적합한","B2"),
("adequate","adj","충분한, 적절한","B2"),
("sufficient","adj","충분한","B2"),
("ample","adj","충분한, 넉넉한","C1"),
("abundant","adj","풍부한","B2"),
("plentiful","adj","풍부한","B2"),
("scarce","adj","부족한, 드문","B2"),
("sparse","adj","드문드문한, 희박한","C1"),
("deficient","adj","부족한, 결핍된","C1"),
("inadequate","adj","불충분한","B2"),
("insufficient","adj","불충분한","B2"),
("meager","adj","빈약한, 메마른","C2"),
("finite","adj","유한한","C1"),
("infinite","adj","무한한","B2"),
("boundless","adj","무한한","C1"),
("static","adj","정적인, 고정된","C1"),
("dynamic","adj","역동적인","B2"),
("fluid","adj","유동적인","C1"),
("volatile","adj","변덕스러운, 불안정한","C2"),
("stable","adj","안정된","B2"),
("robust","adj","견고한, 튼튼한","C1"),
("resilient","adj","회복력 있는, 탄력적인","C1"),
("fragile","adj","취약한, 깨지기 쉬운","B2"),
("vulnerable","adj","취약한","B2"),
("susceptible","adj","영향받기 쉬운, 민감한","C1"),
("prone","adj","~하기 쉬운","B2"),
("liable","adj","~하기 쉬운, 책임이 있는","C1"),
("resistant","adj","저항하는, 잘 견디는","B2"),
("immune","adj","면역이 있는, 영향받지 않는","B2"),
("indifferent","adj","무관심한","B2"),
("neutral","adj","중립적인","B2"),
("impartial","adj","공정한, 편견 없는","C1"),
("unbiased","adj","편견 없는","C1"),
("objective","adj","객관적인","B2"),
("subjective","adj","주관적인","B2"),
("biased","adj","편향된","B2"),
("partisan","adj","당파적인, 편파적인","C2"),
("dogmatic","adj","독단적인","C2"),
("orthodox","adj","정통의, 전통적인","C1"),
("unorthodox","adj","비정통적인","C2"),
("conventional","adj","관습적인, 종래의","B2"),
("traditional","adj","전통적인","B2"),
("contemporary","adj","현대의, 동시대의","B2"),
("modern","adj","현대의","B2"),
("innovative","adj","혁신적인","B2"),
("novel","adj","새로운, 참신한","C1"),
("unprecedented","adj","전례 없는","C1"),
("radical","adj","급진적인, 근본적인","B2"),
("revolutionary","adj","혁명적인","B2"),
("progressive","adj","진보적인","B2"),
("obsolete","adj","구식의, 쓸모없어진","C1"),
("archaic","adj","고풍의, 낡은","C2"),
("outdated","adj","구식의","B2"),
("antiquated","adj","구식의, 시대에 뒤진","C2"),
("rudimentary","adj","기초적인, 초보적인","C2"),
("elaborate","adj","정교한, 공들인","B2"),
("intricate","adj","복잡한, 정교한","C1"),
("complex","adj","복잡한","B2"),
("complicated","adj","복잡한","B2"),
("convoluted","adj","복잡한, 뒤얽힌","C2"),
("sophisticated","adj","정교한, 세련된","B2"),
("refined","adj","세련된, 정제된","B2"),
("crude","adj","조잡한, 대략적인","B2"),
("simplistic","adj","지나치게 단순화한","C1"),
("superficial","adj","피상적인, 표면적인","C1"),
("cursory","adj","대충하는, 피상적인","C2"),
("profound","adj","심오한, 깊은","C1"),
("deep","adj","깊은","B2"),
("penetrating","adj","날카로운, 통찰력 있는","C1"),
("insightful","adj","통찰력 있는","B2"),
("perceptive","adj","통찰력 있는, 예리한","C1"),
("astute","adj","기민한, 예리한","C2"),
("shrewd","adj","영리한, 판단이 빠른","C1"),
("discerning","adj","안목 있는, 분별력 있는","C2"),
("prudent","adj","신중한, 분별 있는","C1"),
("judicious","adj","분별 있는, 현명한","C2"),
("circumspect","adj","신중한","C2"),
("cautious","adj","조심스러운","B2"),
("meticulous","adj","꼼꼼한","C1"),
("diligent","adj","성실한, 부지런한","B2"),
("assiduous","adj","근면한, 부지런한","C2"),

# ---- Academic adverbs / connectives / hedging ----
("consequently","adv","결과적으로","B2"),
("therefore","adv","그러므로","B2"),
("thus","adv","따라서, 그리하여","B2"),
("hence","adv","그러므로, 이런 이유로","B2"),
("accordingly","adv","그에 따라, 따라서","B2"),
("subsequently","adv","그 후에, 이어서","B2"),
("previously","adv","이전에","B2"),
("hitherto","adv","지금까지","C2"),
("henceforth","adv","이후로, 지금부터","C2"),
("simultaneously","adv","동시에","B2"),
("concurrently","adv","동시에","C1"),
("respectively","adv","각각","B2"),
("relatively","adv","상대적으로, 비교적","B2"),
("comparatively","adv","비교적","B2"),
("proportionally","adv","비례하여","C1"),
("substantially","adv","상당히, 실질적으로","B2"),
("considerably","adv","상당히","B2"),
("significantly","adv","상당히, 유의미하게","B2"),
("markedly","adv","현저하게","C1"),
("notably","adv","특히, 현저히","B2"),
("appreciably","adv","눈에 띄게, 상당히","C2"),
("marginally","adv","약간, 미미하게","C1"),
("negligibly","adv","무시할 정도로","C2"),
("predominantly","adv","주로, 대부분","C1"),
("primarily","adv","주로","B2"),
("chiefly","adv","주로","B2"),
("largely","adv","대체로, 주로","B2"),
("mainly","adv","주로","B2"),
("essentially","adv","본질적으로, 근본적으로","B2"),
("fundamentally","adv","근본적으로","B2"),
("intrinsically","adv","본질적으로","C2"),
("inherently","adv","본질적으로, 선천적으로","C1"),
("ostensibly","adv","표면상, 겉보기에는","C2"),
("seemingly","adv","겉보기에는","B2"),
("apparently","adv","보아하니, 명백히","B2"),
("evidently","adv","분명히, 명백히","B2"),
("manifestly","adv","명백하게","C2"),
("presumably","adv","아마도, 추정컨대","B2"),
("supposedly","adv","추정상, 아마","B2"),
("allegedly","adv","전해지는 바에 따르면","C1"),
("arguably","adv","거의 틀림없이, 아마도","C1"),
("conceivably","adv","아마도, 생각건대","C2"),
("plausibly","adv","그럴듯하게","C2"),
("ostensibly","adv","표면상","C2"),
("nominally","adv","명목상","C2"),
("theoretically","adv","이론상","B2"),
("hypothetically","adv","가정하여","C1"),
("empirically","adv","경험적으로, 실증적으로","C1"),
("statistically","adv","통계적으로","B2"),
("systematically","adv","체계적으로","B2"),
("methodically","adv","체계적으로","C1"),
("rigorously","adv","엄밀하게","C1"),
("precisely","adv","정확히","B2"),
("explicitly","adv","명시적으로","C1"),
("implicitly","adv","암시적으로","C1"),
("invariably","adv","변함없이, 언제나","C1"),
("consistently","adv","일관되게","B2"),
("uniformly","adv","한결같이, 균일하게","C1"),
("universally","adv","보편적으로","B2"),
("collectively","adv","집합적으로, 총체적으로","B2"),
("cumulatively","adv","누적적으로","C1"),
("conversely","adv","반대로","C1"),
("contrarily","adv","반대로","C2"),
("alternatively","adv","대안적으로, 그렇지 않으면","B2"),
("otherwise","adv","그렇지 않으면, 달리","B2"),
("nonetheless","adv","그럼에도 불구하고","B2"),
("nevertheless","adv","그럼에도 불구하고","B2"),
("notwithstanding","adv","그럼에도 불구하고","C2"),
("regardless","adv","상관없이","B2"),
("albeit","adv","비록 ~일지라도","C1"),
("whereas","adv","~인 반면에","B2"),
("moreover","adv","게다가, 더욱이","B2"),
("furthermore","adv","더욱이, 게다가","B2"),
("additionally","adv","게다가, 추가로","B2"),
("likewise","adv","마찬가지로","B2"),
("similarly","adv","유사하게","B2"),
("correspondingly","adv","상응하여","C1"),
("analogously","adv","유사하게","C2"),
("namely","adv","즉, 다시 말해","B2"),
("specifically","adv","구체적으로, 특히","B2"),
("particularly","adv","특히","B2"),
("notably","adv","특히","B2"),
("incidentally","adv","덧붙여 말하면, 우연히","C1"),
("ultimately","adv","궁극적으로, 결국","B2"),
("eventually","adv","결국","B2"),
("initially","adv","처음에","B2"),
("originally","adv","원래, 본래","B2"),
("increasingly","adv","점점 더","B2"),
("progressively","adv","점진적으로","C1"),
("gradually","adv","점차적으로","B2"),
("abruptly","adv","갑자기","C1"),
("sporadically","adv","산발적으로","C2"),
("intermittently","adv","간헐적으로","C2"),
("periodically","adv","주기적으로","B2"),
("perpetually","adv","영구히, 끊임없이","C1"),
("indefinitely","adv","무기한으로","C1"),
("temporarily","adv","일시적으로","B2"),
("provisionally","adv","잠정적으로","C2"),
("tentatively","adv","잠정적으로, 시험적으로","C1"),
("purportedly","adv","전해지는 바로는","C2"),
("undeniably","adv","부인할 수 없이","C1"),
("indisputably","adv","의심할 여지없이","C2"),
("unequivocally","adv","명백히","C2"),
("categorically","adv","단정적으로, 절대적으로","C2"),
("inevitably","adv","불가피하게","B2"),
("necessarily","adv","반드시, 필연적으로","B2"),
("paradoxically","adv","역설적으로","C1"),
("ironically","adv","아이러니하게도","B2"),
("crucially","adv","결정적으로","C1"),
("critically","adv","결정적으로, 비판적으로","B2"),
("notoriously","adv","악명 높게","C1"),

# ---- Additional academic nouns/verbs/adjectives to round out ----
("advent","n","도래, 출현","C1"),
("aftermath","n","여파, 후유증","C1"),
("analogy","n","유추, 비유","B2"),
("anomaly","n","이례, 변칙","C1"),
("antithesis","n","대조, 정반대","C2"),
("apparatus","n","기구, 장치","C1"),
("bias","n","편향","B2"),
("caveat","n","단서, 경고","C2"),
("cohort","n","집단, 동년배 집단","C2"),
("connotation","n","함축","C2"),
("corollary","n","필연적 결과, 따름정리","C2"),
("dichotomy","n","이분법, 양분","C2"),
("dilemma","n","딜레마, 진퇴양난","B2"),
("dogma","n","독단, 교리","C2"),
("duality","n","이중성","C2"),
("emphasis","n","강조","B2"),
("epitome","n","전형, 축약","C2"),
("equivalence","n","등가, 동등","C1"),
("fallacy","n","오류, 그릇된 생각","C1"),
("juxtaposition","n","병치, 나란히 놓음","C2"),
("legacy","n","유산","B2"),
("mainstay","n","중심, 기둥","C2"),
("manifesto","n","선언문","C1"),
("milestone","n","이정표, 중대 사건","B2"),
("nexus","n","연결, 중심","C2"),
("paradox","n","역설","C1"),
("parallel","n","유사점, 평행","B2"),
("pendulum","n","진자, 오가는 추세","C1"),
("phenomenon","n","현상","B2"),
("plethora","n","과다, 과잉","C2"),
("premise","n","전제","C1"),
("presupposition","n","전제, 가정","C2"),
("proxy","n","대리, 대용","C1"),
("recourse","n","의지, 의존","C2"),
("spectrum","n","스펙트럼, 범위","C1"),
("subtext","n","숨은 의미","C2"),
("synergy","n","시너지, 상승효과","C1"),
("threshold","n","문턱, 기준점","C1"),
("trajectory","n","궤도, 궤적","C1"),
("underpinning","n","기반, 토대","C2"),
("watershed","n","분수령, 전환점","C2"),
("nuance","n","뉘앙스, 미묘한 차이","C1"),
("premise","n","전제","C1"),
("paradigm","n","패러다임","C1"),
("construct","n","구성체","C1"),
("dimension","n","차원","B2"),
("determinant","n","결정 요인","C2"),
("variable","n","변수","B2"),
("byproduct","n","부산물","C1"),
("offshoot","n","파생물, 분파","C2"),
("derivative","n","파생물","C1"),
("variant","n","변형, 변종","B2"),
("hybrid","n","혼합물, 잡종","B2"),
("amalgam","n","혼합물","C2"),
("synthesis","n","종합","C1"),
("compound","n","복합체, 화합물","B2"),
("aggregate","n","집합체","C1"),
("array","n","배열, 다수","C1"),
("hierarchy","n","위계","C1"),
("continuum","n","연속체","C2"),
("gradient","n","기울기, 변화도","C1"),
("increment","n","증가분","C1"),
("differential","n","차이, 격차","C2"),
("quotient","n","몫, 지수","C2"),
("coefficient","n","계수","C2"),
("magnitude","n","크기, 규모","C1"),
("amplitude","n","진폭, 크기","C2"),
("frequency","n","빈도","B2"),
("density","n","밀도","B2"),
("intensity","n","강도, 세기","B2"),
("velocity","n","속도","B2"),
("momentum","n","추진력, 탄력","C1"),
("inertia","n","관성, 타성","C2"),
("equilibrium","n","평형","C1"),
("threshold","n","임계값","C1"),
("saturation","n","포화","C1"),
("residue","n","잔여물, 잔류물","C1"),
("remnant","n","잔여, 나머지","C1"),
("surplus","n","잉여, 흑자","B2"),
("deficit","n","적자, 부족","B2"),
("shortfall","n","부족분","C1"),
("discrepancy","n","불일치","C1"),
("anomaly","n","변칙, 이례","C1"),
("outlier","n","이상치, 예외적 존재","C2"),
("aberration","n","일탈, 변칙","C2"),
("deviation","n","편차, 일탈","C1"),
("norm","n","규범, 표준","C1"),
("baseline","n","기준선","C1"),
("benchmark","n","기준점","C1"),
("yardstick","n","기준, 척도","C2"),
("touchstone","n","시금석, 기준","C2"),
("criterion","n","기준","B2"),
("hallmark","n","특징, 품질 보증","C1"),
("signature","n","특징, 고유한 표시","B2"),
("hallmark","n","전형적 특징","C1"),
("premise","n","전제","C1"),
("underpin","v","뒷받침하다, 근거가 되다","C1"),
("underlie","v","기초가 되다, 근저에 있다","C1"),
("hinge","v","~에 달려 있다","C1"),
("pertain","v","관련되다, 적용되다","C1"),
("correspond","v","일치하다","B2"),
("coincide","v","일치하다","C1"),
("overlap","v","겹치다, 중복되다","B2"),
("intersect","v","교차하다","C1"),
("interconnect","v","상호 연결되다","C1"),
("intertwine","v","뒤얽히다, 엮이다","C2"),
("permeate","v","스며들다, 배어들다","C2"),
("pervade","v","만연하다, 스며들다","C2"),
("saturate","v","포화시키다, 흠뻑 적시다","C1"),
("infuse","v","불어넣다, 주입하다","C2"),
("imbue","v","불어넣다, 스미게 하다","C2"),
("permeate","v","침투하다","C2"),
("dilute","v","희석하다, 약화시키다","C1"),
("distill","v","증류하다, 추출하다","C2"),
("crystallize","v","구체화되다, 명확해지다","C2"),
("consolidate","v","통합하다, 굳히다","C1"),
("delineate","v","윤곽을 그리다","C2"),
("demarcate","v","경계를 정하다","C2"),
("circumscribe","v","제한하다, 둘러싸다","C2"),
("encapsulate","v","요약하다, 압축하다","C2"),
("epitomize","v","전형을 보이다","C2"),
("typify","v","전형적으로 나타내다","C1"),
("personify","v","의인화하다, 전형이 되다","C1"),
("symbolize","v","상징하다","B2"),
("signify","v","의미하다","C1"),
("presuppose","v","전제하다","C2"),
("predicate","v","근거를 두다","C2"),
("premise","v","전제로 하다","C2"),
("posit","v","상정하다, 가정하다","C2"),
("stipulate","v","명시하다","C2"),
("delimit","v","한정하다, 범위를 정하다","C2"),
("quantify","v","수량화하다","C1"),
("qualify","v","자격을 주다, 한정하다","B2"),
("modulate","v","조절하다","C2"),
("calibrate","v","조정하다, 눈금을 매기다","C2"),
("recalibrate","v","재조정하다","C2"),
("extrapolate","v","외삽하다, 추론하다","C2"),
("interpolate","v","보간하다, 삽입하다","C2"),
("approximate","v","근사하다","C1"),
("estimate","v","추정하다","B2"),
("gauge","v","측정하다, 가늠하다","C1"),
("ascertain","v","확인하다, 알아내다","C1"),
("discern","v","식별하다","C2"),
("pinpoint","v","정확히 지적하다","C1"),
("delineate","v","기술하다","C2"),
("expound","v","설명하다","C2"),
("elucidate","v","명료하게 설명하다","C2"),
("clarify","v","명확히 하다","B2"),
("illuminate","v","밝히다, 조명하다","C1"),
("shed","v","(빛을) 비추다, 밝히다","B2"),
("expose","v","드러내다, 노출시키다","B2"),
("reveal","v","드러내다, 밝히다","B2"),
("unveil","v","공개하다, 밝히다","C1"),
("uncover","v","밝혀내다, 폭로하다","B2"),
("disclose","v","공개하다, 밝히다","C1"),
("divulge","v","누설하다, 밝히다","C2"),
("manifest","v","나타나다, 드러내다","C1"),
("surface","v","표면화되다, 드러나다","B2"),
("materialize","v","실현되다, 나타나다","C1"),
("actualize","v","실현하다","C2"),
("realize","v","실현하다, 깨닫다","B2"),
("instantiate","v","구체화하다, 예시하다","C2"),
("operationalize","v","실행 가능하게 하다","C2"),
("implement","v","시행하다","B2"),
("enact","v","제정하다, 시행하다","C1"),
("promulgate","v","공포하다, 널리 알리다","C2"),
("propound","v","제기하다, 내놓다","C2"),
("advance","v","제기하다, 진전시키다","B2"),
("put","v","제시하다, 표현하다","B2"),
("frame","v","표현하다, 틀 짓다","B2"),
("cast","v","묘사하다, 제시하다","B2"),
("couch","v","(특정 방식으로) 표현하다","C2"),
("pose","v","제기하다, 자세를 취하다","B2"),
("raise","v","제기하다","B2"),
("broach","v","(화제를) 꺼내다","C2"),
("premise","v","전제하다","C2"),
("outline","v","개요를 서술하다","B2"),
("sketch","v","약술하다, 스케치하다","B2"),
("map","v","연관 짓다, 도식화하다","B2"),
("chart","v","도표화하다, 기록하다","B2"),
("plot","v","도표로 나타내다, 구상하다","B2"),
("tabulate","v","표로 만들다","C2"),
("catalog","v","목록화하다","C1"),
("inventory","v","목록을 작성하다","C2"),
("chronicle","v","연대순으로 기록하다","C2"),
("document","v","기록하다, 문서화하다","B2"),
("record","v","기록하다","B2"),
("register","v","등록하다, 기록되다","B2"),
("log","v","기록하다","B2"),
("annotate","v","주석을 달다","C2"),
("footnote","v","각주를 달다","C2"),
("cross-reference","v","상호 참조하다","C2"),
("collate","v","대조하다, 정리하다","C2"),
("cross-check","v","교차 확인하다","C1"),
("reconcile","v","조정하다, 대조하다","C1"),
("harmonize","v","조화시키다","C1"),
("align","v","일치시키다, 정렬하다","B2"),
("attune","v","맞추다, 조율하다","C2"),
("orient","v","방향을 맞추다, 적응시키다","C1"),
("reorient","v","방향을 재조정하다","C2"),
("recalibrate","v","재조정하다","C2"),
("readjust","v","재조정하다","C1"),
("reconfigure","v","재구성하다","C2"),
("restructure","v","재구성하다, 개편하다","C1"),
("reorganize","v","재편성하다","B2"),
("reformulate","v","재구성하다, 다시 공식화하다","C2"),
("redefine","v","재정의하다","C1"),
("reassess","v","재평가하다","C1"),
("reevaluate","v","재평가하다","C1"),
("reconsider","v","재고하다","B2"),
("revisit","v","다시 살펴보다","C1"),
("reexamine","v","재검토하다","C1"),
("scrutinize","v","면밀히 조사하다","C1"),
("interrogate","v","심문하다, 면밀히 검토하다","C2"),
("query","v","질문하다, 의문을 제기하다","C1"),
("problematize","v","문제화하다","C2"),
("complicate","v","복잡하게 하다","B2"),
("nuance","v","미묘한 차이를 더하다","C2"),
("qualify","v","단서를 달다, 한정하다","B2"),
("temper","v","완화하다, 조절하다","C2"),
("moderate","v","완화하다, 조정하다","B2"),
("modulate","v","조절하다","C2"),
("attenuate","v","약화시키다, 감쇠시키다","C2"),
("dampen","v","약화시키다, 억누르다","C1"),
("curtail","v","축소하다, 단축하다","C2"),
("truncate","v","줄이다, 자르다","C2"),
("abbreviate","v","축약하다, 단축하다","C1"),
("condense","v","응축하다","C1"),
("abridge","v","요약하다, 단축하다","C2"),
("summarize","v","요약하다","B2"),
("recap","v","요약하다","B2"),
("distill","v","추출하다, 정수를 뽑다","C2"),
("extrapolate","v","추정하다, 확대 해석하다","C2"),
("generalize","v","일반화하다","B2"),
("universalize","v","보편화하다","C2"),
("particularize","v","구체적으로 명시하다","C2"),
("specify","v","명시하다","B2"),
("itemize","v","항목별로 적다","C2"),
("enumerate","v","열거하다","C2"),
("list","v","열거하다, 나열하다","B2"),
("rank","v","순위를 매기다","B2"),
("rate","v","평가하다, 등급을 매기다","B2"),
("grade","v","등급을 매기다","B2"),
("prioritize","v","우선순위를 정하다","B2"),
("weight","v","가중치를 두다","C1"),
("emphasize","v","강조하다","B2"),
("downplay","v","경시하다, 대수롭지 않게 하다","C1"),
("understate","v","축소해서 말하다","C1"),
("overstate","v","과장하다","C1"),
("exaggerate","v","과장하다","B2"),
("overestimate","v","과대평가하다","B2"),
("underestimate","v","과소평가하다","B2"),
("misjudge","v","잘못 판단하다","C1"),
("misconstrue","v","오해하다, 잘못 해석하다","C2"),
("misinterpret","v","잘못 해석하다","C1"),
("conflate","v","융합하다, 혼동하다","C2"),
("confound","v","혼동시키다, 당황케 하다","C2"),
("obscure","v","모호하게 하다, 가리다","C1"),
("blur","v","흐리게 하다, 모호하게 하다","B2"),
("distort","v","왜곡하다","B2"),
("skew","v","왜곡하다, 편향되게 하다","C1"),
("misrepresent","v","잘못 전하다, 왜곡하다","C1"),
("oversimplify","v","지나치게 단순화하다","C1"),
("generalize","v","일반화하다","B2"),
("stereotype","v","고정관념화하다","C1"),
("essentialize","v","본질화하다","C2"),
("reify","v","구체화하다, 물화하다","C2"),
("problematize","v","문제 삼다","C2"),
("contextualize","v","맥락화하다","C2"),
("historicize","v","역사적으로 파악하다","C2"),
("situate","v","위치시키다, 자리매김하다","C1"),
("position","v","자리매김하다","B2"),
("locate","v","위치를 찾다, 두다","B2"),
("embed","v","끼워 넣다, 내재시키다","C1"),
("entrench","v","확고히 하다, 고착시키다","C2"),
("ingrain","v","깊이 배게 하다","C2"),
("instill","v","주입하다, 심어주다","C1"),
("inculcate","v","주입하다, 심어주다","C2"),
("indoctrinate","v","사상을 주입하다","C2"),
("condition","v","길들이다, 조건화하다","B2"),
("predispose","v","~하는 경향을 갖게 하다","C2"),
("incline","v","기울게 하다, ~하는 경향을 갖게 하다","C1"),
("dispose","v","~하는 경향을 갖게 하다","C1"),
("orient","v","지향하게 하다","C1"),
("gear","v","맞추다, 조정하다","C1"),
("tailor","v","맞추다, 조정하다","C1"),
("customize","v","맞춤화하다","B2"),
("adapt","v","적응시키다, 조정하다","B2"),
("accommodate","v","수용하다, 맞추다","B2"),
("cater","v","(요구를) 충족시키다","B2"),
("reconcile","v","조화시키다","C1"),
("integrate","v","통합하다","B2"),
("assimilate","v","동화시키다, 흡수하다","C1"),
("absorb","v","흡수하다","B2"),
("internalize","v","내면화하다","C2"),
("appropriate","v","도용하다, 전용하다","C2"),
("co-opt","v","끌어들이다, 흡수하다","C2"),
("subsume","v","포섭하다, 포함시키다","C2"),
("subordinate","v","종속시키다","C1"),
("relegate","v","격하시키다, 좌천시키다","C2"),
("marginalize","v","주변화하다, 소외시키다","C1"),
("privilege","v","특권을 주다, 우대하다","C2"),
("prioritize","v","우선시하다","B2"),
("foreground","v","전면에 내세우다","C2"),
("highlight","v","부각하다","B2"),
("spotlight","v","조명하다, 주목하게 하다","C1"),
("accentuate","v","두드러지게 하다, 강조하다","C1"),
("magnify","v","확대하다, 과장하다","C1"),
("intensify","v","강화하다, 심화시키다","B2"),
("heighten","v","고조시키다, 높이다","C1"),
("escalate","v","격화되다, 확대되다","C1"),
("compound","v","악화시키다, 가중시키다","C2"),
("aggravate","v","악화시키다","C1"),
("worsen","v","악화되다","B2"),
("deteriorate","v","악화되다","B2"),
("degenerate","v","퇴화하다, 악화되다","C1"),
("degrade","v","저하시키다, 분해되다","C1"),
("erode","v","침식하다, 약화시키다","C1"),
("corrode","v","부식시키다, 좀먹다","C2"),
("decay","v","부패하다, 쇠퇴하다","B2"),
("decline","v","감소하다, 쇠퇴하다","B2"),
("dwindle","v","점점 줄어들다","C1"),
("wane","v","약해지다, 이지러지다","C2"),
("recede","v","물러나다, 약해지다","C1"),
("subside","v","가라앉다, 진정되다","C1"),
("abate","v","약해지다, 완화되다","C2"),
("plateau","v","정체하다, 안정기에 접어들다","C2"),
("stabilize","v","안정시키다","B2"),
("normalize","v","정상화하다","C1"),
("regularize","v","정규화하다","C2"),
("rationalize","v","합리화하다","C1"),
("optimize","v","최적화하다","C1"),
("streamline","v","간소화하다","C1"),
("expedite","v","신속히 처리하다","C2"),
("hasten","v","재촉하다, 서두르다","C1"),
("prolong","v","연장하다, 늘이다","B2"),
("protract","v","오래 끌다, 연장하다","C2"),
("perpetuate","v","영속시키다, 지속시키다","C2"),
("sustain","v","지속하다","B2"),
("maintain","v","유지하다","B2"),
("uphold","v","지지하다, 유지하다","C1"),
("preserve","v","보존하다","B2"),
("safeguard","v","보호하다, 지키다","C1"),
("secure","v","확보하다, 안전하게 하다","B2"),
("ensure","v","보장하다, 확실히 하다","B2"),
("guarantee","v","보장하다","B2"),
("warrant","v","보증하다, 정당화하다","C1"),
("underwrite","v","보증하다, 지원하다","C2"),
("subsidize","v","보조금을 지급하다","C1"),
("finance","v","자금을 대다","B2"),
("fund","v","자금을 제공하다","B2"),
("allocate","v","배정하다","B2"),
("apportion","v","배분하다, 할당하다","C2"),
("distribute","v","분배하다","B2"),
("disperse","v","분산시키다, 흩어지다","C1"),
("dispense","v","나누어 주다, 시행하다","C1"),
("disseminate","v","전파하다","C2"),
("proliferate","v","확산하다","C2"),
("propagate","v","전파하다, 번식시키다","C2"),
("perpetuate","v","영속시키다","C2"),
("engender","v","낳다, 야기하다","C2"),
("beget","v","야기하다, 낳다","C2"),
("spawn","v","낳다, 야기하다","C1"),
("breed","v","야기하다, 번식시키다","B2"),
("foster","v","조성하다","C1"),
("incubate","v","배양하다, 잠복하다","C2"),
("germinate","v","싹트다, 발아하다","C2"),
("sprout","v","싹트다, 생겨나다","B2"),
("burgeon","v","급성장하다, 싹트다","C2"),
("blossom","v","꽃피우다, 번성하다","B2"),
("mushroom","v","급증하다","C1"),
("snowball","v","눈덩이처럼 커지다","C2"),
("skyrocket","v","급등하다","C1"),
("plummet","v","급락하다, 곤두박질치다","C1"),
("plunge","v","급락하다, 뛰어들다","B2"),
("surge","v","급등하다, 밀려들다","B2"),
("soar","v","치솟다, 급등하다","B2"),
("spike","v","급등하다","B2"),
("taper","v","점점 가늘어지다, 줄다","C2"),
("dwindle","v","줄어들다","C1"),
("contract","v","수축하다","B2"),
("shrink","v","줄어들다, 수축하다","B2"),
("stagnate","v","정체되다, 침체되다","C1"),
("languish","v","시들다, 침체되다","C2"),
("flounder","v","허둥대다, 고전하다","C2"),
("falter","v","흔들리다, 주춤하다","C1"),
("waver","v","흔들리다, 망설이다","C1"),
("oscillate","v","진동하다, 오락가락하다","C2"),
("vacillate","v","동요하다, 망설이다","C2"),
("fluctuate","v","변동하다","C1"),
("gyrate","v","급변하다, 회전하다","C2"),
("stabilize","v","안정되다","B2"),
("equilibrate","v","평형을 이루다","C2"),
("counterbalance","v","균형을 맞추다, 상쇄하다","C2"),
("offset","v","상쇄하다","C1"),
("compensate","v","보상하다","B2"),
("reciprocate","v","보답하다, 상응하다","C2"),
("correspond","v","상응하다","B2"),
("parallel","v","필적하다, 유사하다","B2"),
("mirror","v","반영하다","C1"),
("echo","v","반영하다, 되풀이하다","B2"),
("resonate","v","공명하다, 반향을 일으키다","C1"),
("reverberate","v","울려 퍼지다, 파급되다","C2"),
("ripple","v","파급되다, 잔물결을 일으키다","C1"),
("cascade","v","연쇄적으로 일어나다","C2"),
("propagate","v","전파되다","C2"),
("permeate","v","스며들다","C2"),

# ---- More cross-disciplinary academic words ----
("advocacy","n","옹호, 지지","C1"),
("affinity","n","친밀감, 유사성","C1"),
("alignment","n","정렬, 제휴","C1"),
("allegiance","n","충성, 지지","C2"),
("ambivalence","n","양가감정, 상반된 감정","C2"),
("analogue","n","유사물, 대응물","C2"),
("antipathy","n","반감, 혐오","C2"),
("apathy","n","무관심","C1"),
("aptitude","n","적성","C1"),
("autonomy","n","자율성, 자치","C1"),
("candor","n","솔직함","C2"),
("catalyst","n","촉매","C1"),
("cohesion","n","응집력, 결속","C1"),
("collaboration","n","협력, 공동 작업","B2"),
("compilation","n","편집, 모음","C1"),
("compliance","n","준수, 순응","C1"),
("composure","n","침착, 평정","C2"),
("comprehension","n","이해","B2"),
("conception","n","개념, 착상","C1"),
("concurrence","n","동의, 일치","C2"),
("conjecture","n","추측","C2"),
("connotation","n","함축","C2"),
("consensus","n","합의","C1"),
("consortium","n","컨소시엄, 협회","C2"),
("constituency","n","지지층, 선거구","C2"),
("consultation","n","협의, 상담","B2"),
("contingency","n","우발 상황, 만일의 사태","C1"),
("continuum","n","연속체","C2"),
("convergence","n","수렴","C2"),
("conviction","n","확신, 신념","B2"),
("correlation","n","상관관계","C1"),
("corroboration","n","확증","C2"),
("credibility","n","신뢰성","C1"),
("criterion","n","기준","B2"),
("culmination","n","정점, 절정","C1"),
("deference","n","경의, 존중","C2"),
("deficiency","n","결핍, 부족","B2"),
("delineation","n","묘사, 기술","C2"),
("denomination","n","명칭, 종파","C2"),
("depiction","n","묘사","C1"),
("deprivation","n","박탈, 결핍","C1"),
("derivation","n","유래, 도출","C1"),
("determinism","n","결정론","C2"),
("deterrent","n","억제책","C1"),
("deviation","n","일탈","C1"),
("dexterity","n","손재주, 능숙함","C2"),
("dichotomy","n","이분법","C2"),
("differentiation","n","차별화","C1"),
("diffusion","n","확산, 보급","C1"),
("dimension","n","차원","B2"),
("discernment","n","분별력, 안목","C2"),
("disclosure","n","공개, 폭로","C1"),
("discourse","n","담론","C1"),
("discrepancy","n","불일치","C1"),
("discretion","n","재량, 신중함","C1"),
("disequilibrium","n","불균형","C2"),
("disparity","n","격차","C1"),
("disposition","n","성향, 기질","C1"),
("disruption","n","붕괴, 혼란","B2"),
("dissemination","n","전파, 보급","C2"),
("dissent","n","반대, 이의","C1"),
("dissonance","n","불협화음, 부조화","C2"),
("distortion","n","왜곡","C1"),
("divergence","n","분기, 차이","C2"),
("diversification","n","다양화, 다각화","C1"),
("doctrine","n","교리, 학설","C1"),
("domain","n","영역","C1"),
("dominance","n","우세, 지배","B2"),
("duality","n","이중성","C2"),
("duplicity","n","이중성, 기만","C2"),
("efficacy","n","효능, 효험","C2"),
("elaboration","n","상세한 설명, 정교화","C1"),
("emancipation","n","해방","C2"),
("embodiment","n","구현, 화신","C2"),
("empowerment","n","권한 부여","C1"),
("endorsement","n","지지, 보증","C1"),
("enigma","n","수수께끼, 불가사의","C2"),
("entity","n","실체, 존재","B2"),
("enumeration","n","열거","C2"),
("equilibrium","n","평형","C1"),
("equity","n","공정, 형평","C1"),
("equivalence","n","등가","C1"),
("eradication","n","근절","C2"),
("escalation","n","확대, 격화","C1"),
("essence","n","본질","C1"),
("ethos","n","기풍, 정신","C2"),
("evolution","n","진화","B2"),
("exacerbation","n","악화","C2"),
("exemption","n","면제","C1"),
("exertion","n","노력, 행사","C1"),
("exposition","n","설명, 해설","C1"),
("extrapolation","n","외삽, 추정","C2"),
("fabrication","n","날조, 제작","C1"),
("facet","n","측면, 양상","C1"),
("fallacy","n","오류","C1"),
("feasibility","n","실현 가능성","C1"),
("fidelity","n","충실도, 정확성","C1"),
("fluctuation","n","변동","C1"),
("formulation","n","공식화, 표현","C1"),
("fragmentation","n","분열, 파편화","C1"),
("framework","n","틀, 체계","B2"),
("frugality","n","검소, 절약","C2"),
("gradation","n","단계적 변화","C2"),
("gravitas","n","진지함, 무게감","C2"),
("hegemony","n","패권, 주도권","C2"),
("heterogeneity","n","이질성","C2"),
("homogeneity","n","동질성","C2"),
("hypothesis","n","가설","B2"),
("iconography","n","도상학, 상징 체계","C2"),
("idealism","n","이상주의","B2"),
("ideology","n","이념, 이데올로기","B2"),
("idiosyncrasy","n","특이성, 별난 특징","C2"),
("illumination","n","해명, 조명","C1"),
("imbalance","n","불균형","B2"),
("impartiality","n","공정성","C2"),
("impediment","n","장애물","C1"),
("imperative","n","반드시 해야 할 일","C1"),
("implementation","n","실행, 이행","B2"),
("implication","n","함의","B2"),
("imposition","n","부과, 강요","C1"),
("impotence","n","무력함","C2"),
("impulse","n","충동, 자극","B2"),
("inception","n","시작, 개시","C2"),
("inclination","n","경향","C1"),
("incoherence","n","비일관성, 모순","C2"),
("incompatibility","n","양립 불가능성","C1"),
("inconsistency","n","불일치, 모순","B2"),
("increment","n","증가분","C1"),
("indeterminacy","n","불확정성","C2"),
("indifference","n","무관심","B2"),
("indoctrination","n","교화, 세뇌","C2"),
("induction","n","귀납, 도입","C1"),
("inertia","n","관성, 타성","C2"),
("inference","n","추론","C1"),
("influx","n","유입, 쇄도","C1"),
("infrastructure","n","기반 시설","B2"),
("infringement","n","침해, 위반","C1"),
("ingenuity","n","독창성, 기발함","C1"),
("inhibition","n","억제, 억압","C1"),
("initiative","n","주도권, 계획","B2"),
("innovation","n","혁신","B2"),
("insight","n","통찰","B2"),
("instability","n","불안정","B2"),
("instantiation","n","구체화, 예시","C2"),
("integration","n","통합","B2"),
("integrity","n","진실성, 온전함","B2"),
("intensification","n","강화, 심화","C1"),
("interdependence","n","상호 의존","C2"),
("interface","n","접점, 인터페이스","B2"),
("interference","n","간섭, 방해","B2"),
("interpolation","n","보간, 삽입","C2"),
("interpretation","n","해석","B2"),
("intersection","n","교차, 접점","B2"),
("intervention","n","개입, 중재","B2"),
("intricacy","n","복잡함, 정교함","C2"),
("intuition","n","직관","C1"),
("invariance","n","불변성","C2"),
("inversion","n","역전, 반전","C1"),
("irregularity","n","불규칙성","C1"),
("juncture","n","시점, 국면","C2"),
("juxtaposition","n","병치","C2"),
("latitude","n","자유, 재량","C2"),
("legitimacy","n","정당성, 합법성","C1"),
("leverage","n","영향력, 지렛대","C1"),
("longevity","n","장수, 수명","C1"),
("magnitude","n","규모","C1"),
("malfunction","n","오작동, 고장","B2"),
("manifestation","n","징후, 발현","C1"),
("mediation","n","중재, 조정","C1"),
("methodology","n","방법론","C1"),
("modality","n","양식, 양상","C2"),
("modification","n","수정, 변경","B2"),
("momentum","n","추진력, 탄력","C1"),
("morphology","n","형태론, 형태","C2"),
("multiplicity","n","다양성, 다수","C2"),
("mutation","n","돌연변이, 변화","B2"),
("negation","n","부정","C2"),
("neutrality","n","중립","B2"),
("normalization","n","정상화, 표준화","C1"),
("notion","n","관념, 개념","B2"),
("novelty","n","참신함, 새로움","C1"),
("nuance","n","뉘앙스","C1"),
("objectivity","n","객관성","C1"),
("obligation","n","의무","B2"),
("obscurity","n","불명확함, 무명","C1"),
("obsolescence","n","진부화, 노후화","C2"),
("optimization","n","최적화","C1"),
("orientation","n","방향, 성향","B2"),
("origination","n","기원, 시작","C2"),
("oscillation","n","진동, 변동","C2"),
("paradigm","n","패러다임","C1"),
("paradox","n","역설","C1"),
("parameter","n","매개변수, 한도","C1"),
("parity","n","동등, 균형","C2"),
("pathology","n","병리, 병폐","C1"),
("perception","n","지각, 인식","B2"),
("periphery","n","주변부, 가장자리","C2"),
("permanence","n","영속성","C1"),
("permutation","n","순열, 조합","C2"),
("perpetuation","n","영속화","C2"),
("persistence","n","지속성, 끈기","B2"),
("perspective","n","관점","B2"),
("pertinence","n","적절성, 관련성","C2"),
("phenomenon","n","현상","B2"),
("plausibility","n","타당성","C2"),
("plurality","n","복수성, 다수","C1"),
("polarity","n","극성, 양극성","C1"),
("polarization","n","양극화","C1"),
("posterity","n","후세, 후손","C2"),
("postulation","n","가정, 상정","C2"),
("precedent","n","선례","C1"),
("precept","n","교훈, 규범","C2"),
("precision","n","정밀함, 정확성","B2"),
("preconception","n","선입견","C1"),
("predicament","n","곤경, 궁지","C1"),
("predilection","n","선호, 편애","C2"),
("predisposition","n","성향, 기질","C2"),
("preeminence","n","탁월함, 우위","C2"),
("premise","n","전제","C1"),
("preoccupation","n","집착, 몰두","C1"),
("preponderance","n","우세, 다수","C2"),
("prerequisite","n","전제 조건","C1"),
("prescription","n","처방, 규정","B2"),
("presumption","n","추정, 가정","C1"),
("presupposition","n","전제","C2"),
("prevalence","n","만연, 유병률","C1"),
("primacy","n","우위, 최우선","C2"),
("probity","n","정직, 청렴","C2"),
("proclivity","n","성향, 기질","C2"),
("profundity","n","심오함","C2"),
("prognosis","n","예후, 예측","C2"),
("proliferation","n","확산, 급증","C2"),
("prominence","n","두드러짐, 명성","C1"),
("propensity","n","성향","C2"),
("proportionality","n","비례성","C2"),
("proposition","n","명제, 제안","C1"),
("propriety","n","적절성, 예의","C2"),
("prototype","n","원형, 시제품","C1"),
("provenance","n","기원, 출처","C2"),
("proximity","n","근접, 인접","C1"),
("pragmatism","n","실용주의","C1"),
("qualification","n","자격, 단서","B2"),
("quandary","n","곤경, 진퇴양난","C2"),
("quantification","n","수량화","C2"),
("rationale","n","근거, 이론적 설명","C1"),
("rationality","n","합리성","C1"),
("reciprocity","n","상호성, 호혜","C2"),
("reconciliation","n","화해, 조화","C1"),
("rectification","n","시정, 교정","C2"),
("redundancy","n","과잉, 중복","C1"),
("refinement","n","정제, 개선","C1"),
("refutation","n","반박","C2"),
("regression","n","퇴행, 회귀","C1"),
("reinforcement","n","강화, 보강","C1"),
("reiteration","n","반복","C2"),
("relativism","n","상대주의","C2"),
("relevance","n","관련성","B2"),
("reliability","n","신뢰성","B2"),
("reminiscence","n","회상, 추억","C2"),
("remnant","n","잔재, 나머지","C1"),
("renaissance","n","부흥, 재생","C1"),
("repercussion","n","영향, 파장","C1"),
("replication","n","복제, 재현","C1"),
("representation","n","표현, 대표","B2"),
("repository","n","저장소","C2"),
("repudiation","n","거부, 부인","C2"),
("resemblance","n","닮음, 유사성","B2"),
("resilience","n","회복력, 탄력성","C1"),
("resolution","n","해결, 결의","B2"),
("resonance","n","공명, 반향","C1"),
("restitution","n","반환, 배상","C2"),
("restraint","n","자제, 억제","B2"),
("restructuring","n","재편, 구조조정","C1"),
("retention","n","보유, 유지","C1"),
("retrospect","n","회고, 돌이켜봄","C1"),
("revelation","n","폭로, 계시","C1"),
("reversal","n","역전, 반전","B2"),
("rigidity","n","경직성","C1"),
("rigor","n","엄격함, 정밀함","C1"),
("rubric","n","지침, 항목","C2"),
("sanction","n","제재, 승인","C1"),
("saturation","n","포화","C1"),
("scrutiny","n","면밀한 조사","C1"),
("segmentation","n","분할, 세분화","C1"),
("segregation","n","분리, 격리","C1"),
("semblance","n","외관, 겉모습","C2"),
("sensibility","n","감수성, 감각","C2"),
("simulation","n","모의실험","B2"),
("simultaneity","n","동시성","C2"),
("skepticism","n","회의론, 의심","C1"),
("solidarity","n","연대, 결속","C1"),
("specificity","n","구체성, 특이성","C2"),
("spectrum","n","범위, 스펙트럼","C1"),
("speculation","n","추측","C1"),
("spontaneity","n","자발성, 즉흥성","C2"),
("stability","n","안정성","B2"),
("stagnation","n","침체, 정체","C1"),
("standardization","n","표준화","C1"),
("stipulation","n","규정, 조건","C2"),
("stratification","n","계층화","C2"),
("subjectivity","n","주관성","C1"),
("subordination","n","종속","C2"),
("subsidy","n","보조금","B2"),
("substantiation","n","입증","C2"),
("substitution","n","대체","B2"),
("subtlety","n","미묘함","C1"),
("succession","n","연속, 계승","C1"),
("sufficiency","n","충분함","C2"),
("superiority","n","우월성","B2"),
("supposition","n","가정, 추측","C2"),
("suppression","n","억압, 진압","C1"),
("susceptibility","n","민감성, 취약성","C2"),
("symmetry","n","대칭","B2"),
("synchronization","n","동기화","C2"),
("synthesis","n","종합, 합성","C1"),
("systematization","n","체계화","C2"),
("tautology","n","동어 반복","C2"),
("taxonomy","n","분류 체계","C2"),
("temperament","n","기질","C1"),
("tenacity","n","끈기, 완강함","C2"),
("tendency","n","경향","B2"),
("tenet","n","교의, 신조","C2"),
("terminology","n","전문 용어","C1"),
("threshold","n","문턱, 임계점","C1"),
("trajectory","n","궤적, 궤도","C1"),
("transcendence","n","초월","C2"),
("transformation","n","변형","B2"),
("transience","n","일시성, 덧없음","C2"),
("transition","n","전환","B2"),
("transparency","n","투명성","B2"),
("turbulence","n","혼란, 격동","C1"),
("typology","n","유형론, 유형 분류","C2"),
("ubiquity","n","편재, 도처에 있음","C2"),
("unanimity","n","만장일치","C2"),
("uncertainty","n","불확실성","B2"),
("underpinning","n","기반, 토대","C2"),
("uniformity","n","균일성","C1"),
("unpredictability","n","예측 불가능성","C1"),
("utility","n","유용성, 효용","B2"),
("validation","n","입증, 검증","C1"),
("validity","n","타당성","C1"),
("variability","n","가변성","C1"),
("variance","n","분산, 차이","C1"),
("variation","n","변이, 변화","B2"),
("velocity","n","속도","B2"),
("veracity","n","진실성, 정확성","C2"),
("verification","n","검증","C1"),
("versatility","n","다재다능, 융통성","C1"),
("viability","n","실행 가능성","C1"),
("vicinity","n","인근, 부근","C1"),
("vindication","n","정당성 입증","C2"),
("virtue","n","미덕, 장점","B2"),
("volatility","n","변동성","C2"),
("vulnerability","n","취약성","B2"),

# ---- Additional adjectives ----
("aberrant","adj","일탈적인, 변칙적인","C2"),
("abstruse","adj","난해한","C2"),
("acute","adj","심각한, 예리한","B2"),
("adverse","adj","불리한, 부정적인","C1"),
("aesthetic","adj","미적인","B2"),
("affirmative","adj","긍정적인, 확언하는","C1"),
("aggregate","adj","총계의","C1"),
("alleged","adj","주장된, 이른바","C1"),
("ambiguous","adj","모호한","C1"),
("analogous","adj","유사한","C1"),
("anomalous","adj","변칙적인, 이례적인","C2"),
("antithetical","adj","정반대의","C2"),
("apparent","adj","명백한, 겉으로 보이는","B2"),
("arbitrary","adj","임의적인, 자의적인","C1"),
("archaic","adj","고풍의, 낡은","C2"),
("ascertainable","adj","확인 가능한","C2"),
("assertive","adj","단호한, 적극적인","C1"),
("attributable","adj","~에 기인하는","C1"),
("authoritative","adj","권위 있는, 믿을 만한","C1"),
("axiomatic","adj","자명한","C2"),
("benign","adj","온화한, 양성의","C1"),
("categorical","adj","단정적인, 범주적인","C2"),
("causal","adj","인과 관계의","C1"),
("circular","adj","순환적인","B2"),
("cognitive","adj","인지의","C1"),
("cohesive","adj","응집력 있는","C1"),
("collective","adj","집단적인","B2"),
("commensurate","adj","상응하는, 비례하는","C2"),
("compelling","adj","설득력 있는","C1"),
("complacent","adj","자기만족적인, 안일한","C2"),
("compliant","adj","순응하는, 준수하는","C1"),
("concomitant","adj","동반하는, 부수적인","C2"),
("conducive","adj","도움이 되는, 이바지하는","C1"),
("confluent","adj","합류하는","C2"),
("consequential","adj","중대한, 결과로 생기는","C1"),
("conspicuous","adj","눈에 띄는","C1"),
("constructive","adj","건설적인","B2"),
("contentious","adj","논쟁적인","C2"),
("contingent","adj","~에 좌우되는","C2"),
("continuous","adj","연속적인","B2"),
("contradictory","adj","모순되는","B2"),
("conventional","adj","관습적인","B2"),
("correlative","adj","상관적인","C2"),
("credible","adj","신뢰할 만한","C1"),
("cyclical","adj","순환적인, 주기적인","C1"),
("definitive","adj","확정적인","C1"),
("degenerative","adj","퇴행성의","C2"),
("deliberate","adj","의도적인, 신중한","B2"),
("derivative","adj","파생적인, 모방적인","C1"),
("detrimental","adj","해로운","C1"),
("diagnostic","adj","진단의","C1"),
("dialectical","adj","변증법적인","C2"),
("differential","adj","차등적인, 차이의","C2"),
("discernible","adj","식별할 수 있는","C1"),
("discrete","adj","별개의, 분리된","C1"),
("discretionary","adj","재량의","C2"),
("disparate","adj","이질적인, 서로 다른","C2"),
("disproportionate","adj","불균형한","C1"),
("disputable","adj","논쟁의 여지가 있는","C1"),
("divergent","adj","갈라지는, 다른","C1"),
("diverse","adj","다양한","B2"),
("dogmatic","adj","독단적인","C2"),
("dubious","adj","의심스러운","C1"),
("dynamic","adj","역동적인","B2"),
("egalitarian","adj","평등주의의","C2"),
("elaborate","adj","정교한","B2"),
("elusive","adj","파악하기 어려운","C2"),
("embryonic","adj","초기의, 미발달의","C2"),
("eminent","adj","저명한","C1"),
("empirical","adj","경험적인","C1"),
("endemic","adj","고유의, 풍토성의","C2"),
("enduring","adj","지속되는","C1"),
("equitable","adj","공정한","C2"),
("equivalent","adj","동등한","B2"),
("erroneous","adj","잘못된","C1"),
("evocative","adj","연상시키는, 불러일으키는","C2"),
("exemplary","adj","모범적인","C1"),
("exhaustive","adj","철저한","C1"),
("explicit","adj","명시적인","C1"),
("extensive","adj","광범위한","B2"),
("extraneous","adj","관련 없는, 외부의","C2"),
("feasible","adj","실현 가능한","C1"),
("finite","adj","유한한","C1"),
("formative","adj","형성기의, 형성하는","C2"),
("fortuitous","adj","우연한, 뜻밖의","C2"),
("foundational","adj","기초적인","C2"),
("fragmentary","adj","단편적인","C2"),
("gradual","adj","점진적인","B2"),
("holistic","adj","전체론적인","C2"),
("homogeneous","adj","동질의","C2"),
("hypothetical","adj","가설적인","C1"),
("illusory","adj","환상의, 착각의","C2"),
("immutable","adj","불변의","C2"),
("imperceptible","adj","감지할 수 없는","C2"),
("implausible","adj","믿기 어려운","C1"),
("implicit","adj","암시적인","C1"),
("inadvertent","adj","의도치 않은","C2"),
("incompatible","adj","양립할 수 없는","B2"),
("inconceivable","adj","상상할 수 없는","C1"),
("inconsequential","adj","하찮은, 중요하지 않은","C2"),
("incontrovertible","adj","반박할 수 없는","C2"),
("incremental","adj","점진적인","C2"),
("indeterminate","adj","불확정적인","C2"),
("indicative","adj","나타내는, 시사하는","C1"),
("indigenous","adj","토착의, 고유의","C1"),
("indispensable","adj","필수적인","C1"),
("inductive","adj","귀납적인","C2"),
("inevitable","adj","불가피한","B2"),
("inexorable","adj","멈출 수 없는, 냉혹한","C2"),
("inferential","adj","추론적인","C2"),
("innate","adj","선천적인","C1"),
("innumerable","adj","무수한","C1"),
("inordinate","adj","과도한","C2"),
("instrumental","adj","도구적인, 중요한","C1"),
("integral","adj","필수적인","C1"),
("intelligible","adj","이해할 수 있는","C1"),
("interminable","adj","끝없는","C2"),
("intrinsic","adj","본질적인","C1"),
("invariable","adj","불변의","C1"),
("irrefutable","adj","반박할 수 없는","C2"),
("irrelevant","adj","무관한","B2"),
("irreversible","adj","되돌릴 수 없는","C1"),
("latent","adj","잠재하는, 숨어 있는","C2"),
("legitimate","adj","정당한","B2"),
("linear","adj","선형의, 직선의","C1"),
("manifold","adj","다양한, 여러 가지의","C2"),
("marginal","adj","미미한, 주변의","C1"),
("meager","adj","빈약한","C2"),
("methodological","adj","방법론적인","C2"),
("multifaceted","adj","다면적인","C2"),
("mundane","adj","평범한, 일상적인","C1"),
("mutable","adj","변하기 쉬운","C2"),
("negligible","adj","무시할 만한","C1"),
("nominal","adj","명목상의, 이름뿐인","C2"),
("normative","adj","규범적인","C2"),
("noteworthy","adj","주목할 만한","C1"),
("nuanced","adj","미묘한","C2"),
("objective","adj","객관적인","B2"),
("obscure","adj","불분명한","C1"),
("obsolete","adj","구식의","C1"),
("ostensible","adj","표면상의","C2"),
("overarching","adj","가장 중요한, 포괄적인","C2"),
("palpable","adj","뚜렷한, 만져질 듯한","C2"),
("paradoxical","adj","역설적인","C1"),
("paramount","adj","가장 중요한","C2"),
("partial","adj","부분적인, 편파적인","B2"),
("perceptible","adj","인지할 수 있는","C2"),
("peripheral","adj","주변의, 부차적인","C1"),
("permeable","adj","투과성의","C2"),
("pertinent","adj","적절한, 관련 있는","C1"),
("pervasive","adj","만연한","C2"),
("pivotal","adj","중추적인","C1"),
("plausible","adj","그럴듯한","C1"),
("plentiful","adj","풍부한","B2"),
("potent","adj","강력한","C1"),
("pragmatic","adj","실용적인","C1"),
("precarious","adj","불안정한, 위태로운","C1"),
("precise","adj","정밀한","B2"),
("preclusive","adj","배제하는","C2"),
("predominant","adj","우세한","C1"),
("preeminent","adj","탁월한","C2"),
("preliminary","adj","예비의","B2"),
("prevailing","adj","우세한","C1"),
("prevalent","adj","만연한","C1"),
("problematic","adj","문제가 있는","B2"),
("profound","adj","심오한","C1"),
("progressive","adj","점진적인","B2"),
("prolific","adj","다작의, 다산의","C1"),
("prominent","adj","두드러진","B2"),
("provisional","adj","잠정적인","C1"),
("provocative","adj","도발적인, 자극적인","C1"),
("proximate","adj","가장 가까운, 근접한","C2"),
("qualitative","adj","질적인","C1"),
("quantitative","adj","양적인","C1"),
("quintessential","adj","전형적인, 정수의","C2"),
("radical","adj","급진적인, 근본적인","B2"),
("rampant","adj","만연한","C2"),
("recurrent","adj","반복되는","C1"),
("redundant","adj","불필요한, 중복의","C1"),
("relentless","adj","가차 없는, 끊임없는","C1"),
("residual","adj","잔여의, 남은","C1"),
("resilient","adj","회복력 있는","C1"),
("resolute","adj","단호한","C1"),
("reciprocal","adj","상호적인","C2"),
("rigorous","adj","엄격한","C1"),
("robust","adj","견고한","C1"),
("rudimentary","adj","기초적인","C2"),
("salient","adj","현저한","C2"),
("scant","adj","부족한, 얼마 안 되는","C2"),
("seminal","adj","중대한, 획기적인","C2"),
("sequential","adj","순차적인","C1"),
("simultaneous","adj","동시의","B2"),
("skeptical","adj","회의적인","C1"),
("sporadic","adj","산발적인","C2"),
("spurious","adj","가짜의, 허위의","C2"),
("static","adj","정적인","C1"),
("stringent","adj","엄격한","C2"),
("subjective","adj","주관적인","B2"),
("subordinate","adj","종속적인","C1"),
("subsequent","adj","이후의","B2"),
("substantive","adj","실질적인, 중요한","C2"),
("subtle","adj","미묘한","B2"),
("superfluous","adj","불필요한, 남아도는","C2"),
("susceptible","adj","취약한, 민감한","C1"),
("symptomatic","adj","징후를 보이는, 전형적인","C1"),
("synonymous","adj","동의어의, 같은 뜻의","C1"),
("systemic","adj","체계적인, 전신의","C1"),
("tacit","adj","암묵적인","C2"),
("tangential","adj","지엽적인, 벗어난","C2"),
("tenable","adj","옹호할 수 있는","C2"),
("tentative","adj","잠정적인","C1"),
("transient","adj","일시적인, 덧없는","C2"),
("transitory","adj","일시적인","C2"),
("unanimous","adj","만장일치의","C1"),
("unconditional","adj","무조건의","B2"),
("underlying","adj","근본적인, 기저의","C1"),
("undue","adj","지나친, 부당한","C2"),
("unequivocal","adj","명백한","C2"),
("unfounded","adj","근거 없는","C1"),
("uniform","adj","균일한, 획일적인","B2"),
("unilateral","adj","일방적인","C2"),
("unprecedented","adj","전례 없는","C1"),
("unsubstantiated","adj","입증되지 않은","C2"),
("untenable","adj","옹호할 수 없는","C2"),
("valid","adj","타당한","B2"),
("versatile","adj","다재다능한, 다용도의","C1"),
("viable","adj","실행 가능한","C1"),
("vigorous","adj","활발한, 격렬한","B2"),
("volatile","adj","불안정한, 변덕스러운","C2"),
("warranted","adj","정당한","C1"),
("widespread","adj","광범위한","B2"),
]

# Deduplicate by headword (keep first occurrence)
seen = set()
out = []
for en, pos, ko, level in data:
    key = en.lower()
    if key in seen:
        continue
    seen.add(key)
    out.append({"en": en, "pos": pos, "ko": ko, "level": level, "topic": "학술일반"})

# Trim to exactly 1000 with a 40/35/25 B2/C1/C2 spread, sampling evenly
# across the file so all categories (verbs, nouns, adjectives, adverbs) stay represented.
targets = {"B2": 400, "C1": 350, "C2": 250}
by_level = {"B2": [], "C1": [], "C2": []}
for w in out:
    by_level[w["level"]].append(w)

selected = []
for lvl, tgt in targets.items():
    items = by_level[lvl]
    n = len(items)
    if n <= tgt:
        selected.extend(items)
    else:
        # evenly spaced indices across the list
        idxs = sorted({round(i * (n - 1) / (tgt - 1)) for i in range(tgt)})
        # in case rounding collapses some, backfill
        chosen = [items[i] for i in idxs]
        if len(chosen) < tgt:
            extra = [items[i] for i in range(n) if i not in set(idxs)]
            chosen.extend(extra[: tgt - len(chosen)])
        selected.extend(chosen[:tgt])

# Restore original file order for a natural reading sequence
order = {id(w): i for i, w in enumerate(out)}
selected.sort(key=lambda w: order[id(w)])
out = selected

with open("/home/user/voca/wordbooks/toefl-build/poolA.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=None, separators=(",", ":"))

# Report
from collections import Counter
levels = Counter(w["level"] for w in out)
print("TOTAL:", len(out))
print("LEVELS:", dict(levels))
print("B2 %%: %.1f" % (100*levels["B2"]/len(out)))
print("C1 %%: %.1f" % (100*levels["C1"]/len(out)))
print("C2 %%: %.1f" % (100*levels["C2"]/len(out)))
